### ISSUE TITLE
一段时间不操作连接断开

### ISSUE THREAD

**Issue by qibao07** [nirui/sshwifty#100]
### 问题
一段时间不操作连接断开。

### 期望
长时间保持连接不断开。

**Comment by qibao07** [comment]
似乎sshwifty置顶显示是不会断开的，我使用的是chrome浏览器，会不会是浏览器会冻结后台运行的页面，导致心跳停了。

**Comment by nirui** [comment]
Sshwifty连接之后会自动维护和保持连接。正常状态下即使用户不进行任何操作，Sshwifty的连接也不会断开。如果断开了的话，有可能是其他因素导致的（比如操作系统或网络路径上的Timeout、网络不稳定等等）。

如果Sshwifty显示自己的连接正常，而SSH终端断开了，则可能是SSH服务器导致的（比如有闲置超时等等）。

**Comment by qibao07** [comment]
@nirui 用xshell连接是不会断，应该不是SSH服务端导致，还有发现chrome连接后不切换其他标签页或其它窗口，好像也不会断开。搜了一下，chrome从版本79开始（不太确定），就有一个冻结后台的功能。  
[Chrome 79版正式更新！标签冻结、跨设备传文本、沉浸式网页](https://zhuanlan.zhihu.com/p/96894938)

**Comment by nirui** [comment]
如果Chrome加入了这样的限制，我这边也是无能为力的。毕竟Sshwifty的前端也只是个网页，能操作的权限和其他网页没什么区别 :(

**Comment by qibao07** [comment]
感谢作者回复，sshwifty还是非常好用的。

**Comment by qibao07** [comment]
### 问题描述
后台运行的标签页，5分钟后定时任务会变成1分钟最多执行1次。导致心跳频率不能够，造成ws连接中断。
### 解决方法
#### 1. nginx设置超时时间；
```
  proxy_send_timeout 300s;
  proxy_read_timeout 300s;
```

#### 2. sshwifty设置超时时间。
```
  "HeartbeatTimeout": 20,
  "ReadTimeout": 300,
  "WriteTimeout": 300
```

### 参考
* [控制 IntensiveWakeUpThrottling 功能](https://admx.help/?Category=Chrome&Policy=Google.Policies.Chrome::IntensiveWakeUpThrottlingEnabled&Language=zh-cn)

**Comment by qibao07** [comment]
@nirui 你好，使用上面的设置现在已经可以长时间不断开了。不过有一个地方不明白，就是`"HeartbeatTimeout": 20`应该会超时的，这里超时会怎么处理，至少现在不是断开连接的。

**Comment by nirui** [comment]
`HeartbeatTimeout`指示前端每隔20秒发送一次Echo请求，后端收到这个Echo之后会立即回应，前端收到来自后端的回应之后会计算延迟时间并显示在用户界面上（就是左上角的那个延迟计）。

`ReadTimeout`指示后端在TCP连接持续无数据到达的情况下，将会等待多久。300秒是5分钟左右，即如果TCP持续5分钟没有读出数据，Sshwifty后端会断开连接。

`WriteTimeout`指示后端在尝试写入TCP链接时，最大允许的等待时间（即允许`Write`操作执行的时间）。超过这个时间，Sshwifty也会断开连接。

Sshwifty通过`ReadTimeout`和`WriteTimeout`的设置来被动的判断TCP连接的活性。在TCP连接正常的情况下，这两个超时都不会到达，因为`HeartbeatTimeout`每隔20秒就会激发一次`Read`和`Write`操作，这样一来，`ReadTimeout`一定会在`HeartbeatTimeout`周期内被重设，而`WriteTimeout`本身只有在TCP已经被严重阻塞的情况下才**不会**被重设。

**Comment by qibao07** [comment]
@nirui 感谢，大概明白了，一开始以为是Echo时间间隔是固定值（程序里写死的），两次Echo间隔大于`HeartbeatTimeout `就断开。其实，`HeartbeatTimeout `就是Echo时间间隔本身。
