### ISSUE TITLE
[bug]在 Firefox 上无法粘贴

### ISSUE THREAD

**Issue by loveqianool** [nirui/sshwifty#103]
sshwifty:lastest
Windows Firefox 104.0b8（64 位元）

使用快捷键粘贴报以下错误，而鼠标右键粘贴没有任何反应。
`Unable to paste: TypeError: window.navigator.clipboard.readText is not a function. Please try again without using the Control+Shift+V / Shift+Insert hot key`

**Comment by nirui** [comment]
我还没有更新到Firefox 104，但是`Unable to paste: TypeError:`错误其实是在预期之中的，因为Firefox默认没有允许Clipboard API，而上面所提到的设置启用了这个Clipboard API。

奇怪的是鼠标右键也无法粘贴。我这边在Linux下测试了Firefox 103.0.1，鼠标右键粘贴是正常的。如果你愿意的话，可以确认一下右键粘贴是否确实无法工作（而不是回显延迟之类造成的）么？

感谢。
