### ISSUE TITLE
Add Ctrl + T to control keys

### ISSUE THREAD

**Issue by luizfeliperj** [nirui/sshwifty#104]
There should be a Ctrl + T on Control Keys menu, as a regular CTRL+T on the browser start a new tab.

**Comment by nirui** [comment]
Hi,

I have implemented suggested change in d5badd135bf33c3274147ce4c6963270988e2b66 which will be carried in the next release.

I still need a little bit more time to test the code for the release, and if everything goes fine, it should become available within the next 6 hours.

Thank you for your suggestion :D

**Comment by nirui** [comment]
Hi, the version that carries the fix (0.2.27-beta) is released.

I'm going to close this issue for now. Feel free to reopen it if necessary.
