### ISSUE TITLE
cant access with password in local

### ISSUE THREAD

**Issue by masterwishx** [nirui/sshwifty#105]
Tryed with config also with env :  
Using http without cert in 192.168.0.199  

![image](https://user-images.githubusercontent.com/28630321/185624714-c6168e06-e9bf-4376-b9ca-170c534315d8.png)
![image](https://user-images.githubusercontent.com/28630321/185624830-660b35e6-ec7a-49ad-92ae-48d28a01fdf5.png)

**Comment by masterwishx** [comment]
problem fixed sorry

**Comment by m-GDEV** [comment]
@masterwishx what did you do? I'm getting the same error
