### ISSUE TITLE
Demo Problem: Doesn't load (no HTTPS)

### ISSUE THREAD

**Issue by techflashYT** [nirui/sshwifty#109]
Whenever I try to load the demo link, chrome errors out with `ERR_SSL_PROTOCOL_ERR`.  And using standard HTTP is not an option for some reason, it always loads HTTPS.

**Comment by nirui** [comment]
Hello,

The error might have been caused by a misconfiguration on the CDN service. I have corrected the setting, it should work now, please give it another try.

If the problem persists, please let me know, and I'll look further. Thanks!
