### ISSUE TITLE
[Feature Request] - enabling nerd fonts

### ISSUE THREAD

**Issue by jmlc11** [nirui/sshwifty#110]
This would be helpful for when the endpoints have any prompts where its using a nerd font that looks like this:
![image](https://user-images.githubusercontent.com/6006781/190864769-484318fb-e247-4892-9bf3-61747faa5c51.png)
And it wont look like this:
![image](https://user-images.githubusercontent.com/6006781/190864780-762486a0-eb37-485d-864b-9400cc60c1c8.png)

**Comment by waylonwang** [comment]
I have the same issue
<img width="124" alt="屏幕快照 2022-09-18 上午8 40 15" src="https://user-images.githubusercontent.com/7424276/190880812-9d3bed07-8418-4ffa-9107-b700f54c9f1b.png">
<img width="165" alt="屏幕快照 2022-09-18 上午8 39 55" src="https://user-images.githubusercontent.com/7424276/190880816-11432857-9201-493b-ae39-16726d663667.png">

**Comment by waylonwang** [comment]
在 #11 这个issue中看到作者已经处理过这个问题，但是我这为什么还是显示不出图形字体呢？

<img width="597" alt="屏幕快照 2022-09-18 上午10 50 43" src="https://user-images.githubusercontent.com/7424276/190883537-24703a49-283e-4f4f-b7c7-696fa249538c.png">

**Comment by nirui** [comment]
Yes, it is doable.

I've investigated few possibilities and found the best way to implement this feature is to swap [Hack] font (which is the font Sshwifty currently shipped with) with [font-logos]. This should enable *most* logos from Nerd fonts while keeping the our asset size not-too-high.

[Hack]: https://github.com/source-foundry/Hack
[font-logos]: https://github.com/lukas-w/font-logos/issues

![screenshot](https://user-images.githubusercontent.com/30656734/190886206-b75308bc-aeaf-413c-8680-01fd023b4940.png)

**Comment by jmlc11** [comment]
Thanks!

**Comment by waylonwang** [comment]
> Yes, it is doable.
> 
> I've investigated few possibilities and found the best way to implement this feature is to swap [Hack](https://github.com/source-foundry/Hack) font (which is the font Sshwifty currently shipped with) with [@azurity/pure-nerd-font](https://github.com/azurity/pure-nerd-font). This should enable _most_ logos from Nerd fonts while keeping the our asset size not-too-high.
> 
> ![screenshot](https://user-images.githubusercontent.com/30656734/190886206-b75308bc-aeaf-413c-8680-01fd023b4940.png)

我这里就是"\uf015 \uf315"的缺失
<img width="639" alt="屏幕快照 2022-09-19 下午12 08 26" src="https://user-images.githubusercontent.com/7424276/190948531-ab415996-a8fc-4e62-b92a-ef0da7397e83.png">

[@azurity/pure-nerd-font](https://github.com/azurity/pure-nerd-font). 有打算什么时候加入新版本么？

**Comment by nirui** [comment]
@waylonwang 上述变更已经由 57816f731f5a1b35b9689f6eedfc913da27fd2b7 完成，但我还需要进行一些测试，所以还没有合并到master。如果没有其他意外情况，携带这个变更的新版本（0.2.29）大约会在本周五发布。

**Comment by nirui** [comment]
A new version (`0.2.29-beta`) which carries the change mentioned above has been released. Please give it a try and feel free to send feedback.

I'll close this issue for now. Feel free to reopen it if the fix failed to deliver the intended result for you.

**Comment by jmlc11** [comment]
Yes its working very well!
![image](https://user-images.githubusercontent.com/6006781/191344263-2e8fd9e6-1fe0-4993-ab45-8d40aa8b0918.png)
![image](https://user-images.githubusercontent.com/6006781/191344399-4b0e5f95-590d-4a6d-867e-2c2332a4e02d.png)


thank you so much!

**Comment by philippetev** [comment]
Guys, the Nerd Fonts have some updates since version 3.0 regarding the symbol codes, so now some oh-my-posh configs (for example), updated to use the new codes set, are not displayed correctly. Is there anything that can be done about that?

**Comment by nirui** [comment]
Hi @philippetev, can you provide some examples in the format of `echo -e "\uXXXX \uXXXX...."`? Replace `XXXX` with the symbols that are displayed incorrectly (as in [comment 1250179715](https://github.com/nirui/sshwifty/issues/110#issuecomment-1250179715)). I'll take a look on what I can do at my end. Thanks!

**Comment by philippetev** [comment]
This is from my oh-my-posh config:

  [[blocks.segments]]
    foreground = "p:yellow"
    style = "plain"
    template = "<p:green>[</>{{ .Path }}<p:green>]</>"
    type = "path"
    [blocks.segments.properties]
      home_icon = "\udb81\udf3b"
      max_depth = 3
      style = "agnoster_short"
      [blocks.segments.properties.mapped_locations]
        "~/Documents" = "\udb80\ude2c"
        "~/Music" = "\udb80\ude23"
        "~/Pictures" = "\udb80\ude1f"
        "~/Videos" = "\udb80\ude2b"

As you can see, some of the symbols are represented by UTF-16 sequences. That's because those symbols have been moved to the font's 5 digits region.

**Comment by nirui** [comment]
Hi @philippetev, sorry for keep you waiting. I had to wait for an upstream security update before I can release anything.

That said, I have released Sshwifty [version 0.3.4], which should allow newer Nerd Fonts to display correctly (see screenshot below).

But I don't really have any PowerShell installation, thus cannot actually test your configuration. So if the problem still persists for you, please ping me again so I can take another look.

Thanks!

[version 0.3.4]: https://github.com/nirui/sshwifty/releases/tag/0.3.4-beta-release-prebuild

![截图 2023-12-06 15-06-52](https://github.com/nirui/sshwifty/assets/30656734/9fdc54c8-aa14-483b-bdcb-fe679c6907d9)

**Comment by philippetev** [comment]
Just tested it. The above config is now displayed correctly. Thanks!
