### ISSUE TITLE
Connected Before中的标签能否显示成Presets中的Title呢？

### ISSUE THREAD

**Issue by waylonwang** [nirui/sshwifty#111]
如果某个Connected Before中的标签能与某个Presets的内容匹配，直接显示为该Presets的Title体验更好，否则显示的内容长度不够，IP被截断了，无法分辨到底是那个连接IP地址

<img width="467" alt="屏幕快照 2022-09-18 上午9 24 18" src="https://user-images.githubusercontent.com/7424276/190881737-795cd21e-2922-4684-ac11-afa13089a292.png">

**Comment by nirui** [comment]
如果问题是因为列表不够宽所以看不到IP地址的话，我这边扩展那个窗体的宽度大概可以缓解这个问题。

![screen shot](https://user-images.githubusercontent.com/30656734/190889402-aff48284-f9cf-4040-ab4d-365142763429.png)

当然这并不是完美的方案，不过在目前的架构下重新设计列表比较麻烦，我想大概得留到重写的时候再考虑了。

在Connected Before里使用Preset的标题可能会导致用户疑惑，所以大概不是很好的解决方案。

**Comment by nirui** [comment]
携带上述变更的版本（`0.2.29-beta`）已经发布了，你可以下载测试一下。

我这边先将这个Issue关闭了，如果新的版本仍然没有满足你的要求，请重新打开这个Issue，我这边会继续跟进。
