### ISSUE TITLE
New demo website (https://sshwifty-demo.nirui.org) is significantly slower than previous website

### ISSUE THREAD

**Issue by GameParrot** [nirui/sshwifty#113]
When using SSH from https://sshwifty-demo.nirui.org (the new site) instead of https://sshwifty.herokuapp.com (the old one), connection times and pings are like 10 times higher. On https://sshwifty-demo.nirui.org, I get like 500 ms ping. On https://sshwifty.herokuapp.com, the ping is usually under 50 ms.

**Comment by nirui** [comment]
Sorry about that. I'm currently hosting the service on one of my virtual server behind Cloudflare, that might have slowed it down.

I will try to improve that, but if you need higher speed at this moment, please consider to self-host your own Sshwifty instance, it only takes one line of command if you're using Docker. On Heroku that costs around $7 a month and it will have similar speed as our old demo, other vendors such as Linode and DigitalOcean provides similar option at $5 or $10 a month.

**Comment by fu-sen** [comment]
Since recently I came across an instance (VM) of OCI. It's free to launch instances. In addition, you will be able to place instances closer to you.

**Comment by f0rttnite** [comment]
coming here to say i have the same issue

the new site has the most insane delay i've known to man (it can take half a minute for anything i input to register) but the old site has at most a quarter second delay

both of them say the ping's between 50-100ms
