### ISSUE TITLE
升级后的字体显示有点问题

### ISSUE THREAD

**Issue by qibao07** [nirui/sshwifty#114]
macOS12.0.1，chrome浏览器，升级0.2.29-beta-release版本后，发现字体显示有些问题。
1. `cd dirname`文件夹名会有下划线
2. 中括号打括号显示不全，英文字母和中文也有这样的情况
![image](https://user-images.githubusercontent.com/35797132/191675529-b4c14fae-c46d-43e2-8b69-afe5c915d7bd.png)

**Comment by nirui** [comment]
你好，我这边没有运行macOS的设备，请问是否可以协助测试一下？如果可以的话，请先打开 https://xtermjs.org/ ，你会在那个页面上看到一个模拟的终端窗口，那个窗口会回显用户的输入。

请在那个终端窗口输入你在截图中所输入的内容，然后观察字体是否也有显示不全（clipping）的情况（请上传你的截图）。感谢。

此外，`cd dirname`命令出现的下划线似乎由是你所使用的Shell产生的？

**Comment by qibao07** [comment]
下划线确实是shell产生，试过其它ssh客户端了。

[https://xtermjs.org/](https://xtermjs.org/)看起来正常的。
![image](https://user-images.githubusercontent.com/35797132/191736355-e5ee8cfb-01bb-468f-b62b-4bd26418ae66.png)

**Comment by nirui** [comment]
抱歉让你久等了。我这边重新将之前使用的字体（Hack）加回了Sshwifty，但是不确定是否能解决这个问题。

请测试一下 https://test:test@sshwifty-experimental.nirui.org/#+Telnet:sshwifty-telnet-test:5555%7Cutf-8 ，这会打开一个Sshwifty页面并连接到一个能提供回显的Telnet测试服务器。

请利用上面的连接再进行一下之前的输入测试，看修改后的Sshwifty是否解决了问题。

感谢。

**Comment by qibao07** [comment]
问题还是存在。

![image](https://user-images.githubusercontent.com/35797132/191902728-8a9c6a2b-76f6-4f7a-8e9a-5bd6d5796931.png)

**Comment by nirui** [comment]
你好，

我这边又更新了一下 https://test:test@sshwifty-experimental.nirui.org/#+Telnet:sshwifty-telnet-test:5555%7Cutf-8 ，如果方便的话请继续帮忙测试一下。

频繁的打扰你实在是抱歉，可我这边没有可以复现问题的环境，只好要请你帮忙测试了。

感谢！

**Comment by qibao07** [comment]
不碍事的，举手之劳，这次可以了，字符都正常显示了。

![image](https://user-images.githubusercontent.com/35797132/191982980-d770abf9-2d48-4350-8fab-fd6edf8e1873.png)

**Comment by nirui** [comment]
明白了。这个问题大概是由上游的Bug导致的。

目前Sshwifty通过`xtermjs 4.19.0`来提供终端界面，这个版本在字符的纵向对齐上有一些[问题]。xtermjs.org上那个演示终端使用的`xtermjs 4.18.0`其实也有这个故障，但由于那个终端使用了`Cascadia Code`这个字体，所以不明显。而Sshwifty使用的字体是`monospace`，在一些系统上这个字体的字符比较高，让故障变得很明显。

[问题]: https://jsfiddle.net/8wz7nkj5/

好消息是`xtermjs 5.0.0`（也是sshwifty-experimental.nirui.org上测试的版本）貌似对纵向对齐进行了改进，因此字符可以正常显示了。坏消息是这个版本有其他的小故障，比如字符背景颜色设定不正确等等。

我目前的计划是，先将Sshwifty所使用的`xtermjs`更新到`5.0.0`，这样至不太会影响使用。`xtermjs`的其他小故障还是等上游慢慢修复好了。

新版本大概会在明天下午的时候发布，因为我需要时间来检查变更，请耐心等待。

**Comment by qibao07** [comment]
更新0.2.30-beta-release，问题已修复，感谢。🙏
