### ISSUE TITLE
Keyfile backend database

### ISSUE THREAD

**Issue by hsmptg** [nirui/sshwifty#116]
I guess that the main utility of sshwifty is the ability of us open a ssh session with a particular server using just a browser and therefore from anywhere, since when we are at our main PC we probably have more powerful ssh clients to do that.

But if we are "anywhere", we probably do not have the keyfile in that device, so it would be interesting to be able to access that keyfile once we passed the authentication process in sshwifty. If we passed that, we are a trust user and therefore could ask the proper keyfile stored in a database running in the backend where sshwifty was installed, right?

Regards and congratulations for this project

**Comment by nirui** [comment]
Sorry, I'm not really feeling it. Adding database support might increase the maintenance cost both at my end and user end.

If you really REALLY seriously don't want to generate and deploy keyfile to all of your devices (AND you've done the security on your SSH servers), try use Presets. Presets allows you to define a static set of remote endpoints, you can specify the private key there, and then those keys will be downloaded (in cleartext) to the user end once they passed Sshwifty login.

For anything more complex than that, you might want to try [Teleport], which is a full out infrastructure management platform.

[Teleport]: https://github.com/gravitational/teleport

**Comment by hsmptg** [comment]
Yes, I understand that adding a database will increase complexity but what about instead of choosing the key file, we could define the path to the key file we previously saved in the server running sshwifty?

Regarding your suggestion (Teleport), I believe it needs that we install previously in each system we want to access using ssh a particular teleport service (something that I would like to avoid). That is why I am now doing some tests with [Bastillion](https://www.bastillion.io/).

**Comment by nirui** [comment]
If you need a SSH gateway for enterprise/team use case, Bastillion or [Guacamole] are indeed a better fit than Sshwifty.

[Guacamole]: https://guacamole.apache.org/

Sshwifty is trying to be just a SSH client, like (a shrunk down version of) PuTTY that runs on web, so of course you need to bring your own password/private key. It might provide gateway functionality if it fits the goal, but there is no guarantee for anything beyond. Sorry.
