### ISSUE TITLE
Application is closing SSH connections

### ISSUE THREAD

**Issue by bentech4u** [nirui/sshwifty#119]
HI

I have deployed application on docker/container . It is working and disconnecting  connections randomly.

error which i am getting container Instance logs:

```Request ended with error: /sshwifty/socket: websocket: close 1006 (abnormal closure): unexpected EOF```

Could you please help me to fix this

Thanks 
Ben

**Comment by nirui** [comment]
Hello,

The error above usually indicates that the connection between your browser and Sshwifty is lost. Maybe it's a connectivity problem? Try increase `SSHWIFTY_READTIMEOUT` might help, but you need to do more tests in order to determine the proper timeout value for your application (say `120` seconds or more).

**Comment by bentech4u** [comment]
Hello,

Thanks for the explanation,

i have installed/deployed docker on https://mogenius.com , on free tier.

could please let me know how can i change SSHWIFTY_READTIMEOUT for docker instance

**Comment by nirui** [comment]
`SSHWIFTY_READTIMEOUT` is just an normal environment variable. It can be configured via Docker commandline during container creating process. Example: `docker run ... --env SSHWIFTY_READTIMEOUT=120 ...` which will set the read timeout to 120 seconds. It can also be configured via docker-compose.yaml, the section located under `services.<your.service-name>.environment`.

I'm not really familiar with mogenius, maybe they provided a way to allow you to setup environment variables for your container in some configuration file similar to `docker-compose.yaml`?

**Comment by bentech4u** [comment]
Hello,

Thanks for the response,

there was a way to pass Enviornment variables. i redeployed application .

will update status,

Regards,
Ben

**Comment by bentech4u** [comment]
Hi,

Still it is disconnecting, below is the error i got 

![image](https://user-images.githubusercontent.com/4426408/205475717-3016dee2-3b93-440a-a93e-8de66698b262.png)

**Comment by nirui** [comment]
That's odd. Do mogenius supports WebSocket? Sshwifty require WebSocket to run, otherwise the request will also fail.

I searched their website (via `site:mogenius.com websocket` keyword) to see if they've mentioned WebSocket, but found none. This got me to suspect that WebSocket might be currently unsupported on their platform.

**Comment by CJendantix** [comment]
Just my two cents here, but you should probably not be hosting Sshwifty in the cloud, ever. If you are trying to SSH into a server that you physically own, host Sshwifty on that server, otherwise, you should probably be SSHing into it with a local program on your computer.

**Comment by shezxx** [comment]
i've got the same issue - adjusted the timeouts via the conf file, but it keeps dropping connections:

`[INF] Fri, 26 Apr 2024 00:25:49 UTC Sshwifty > Server (0.0.0.0:8182) > Client (172.19.0.1:44542): Request completed: /sshwifty/socket/verify

[WRN] Fri, 26 Apr 2024 00:30:06 UTC Sshwifty > Server (0.0.0.0:8182) > Client (172.19.0.1:44528): Request ended with error: /sshwifty/socket: websocket: close 1006 (abnormal closure): unexpected EOF
`
the global config from json:

` {
      "ListenInterface": "0.0.0.0",
      "ListenPort": 8182,
      "InitialTimeout": 15,
      "ReadTimeout": 120,
      "WriteTimeout": 120,
      "HeartbeatTimeout": 120,
      "ReadDelay": 20,
      "WriteDelay": 20,
      "TLSCertificateFile": "",
      "TLSCertificateKeyFile": "",
      "ServerMessage": "Programmers in China launched an online campaign against [implicitly forced overtime work](https://en.wikipedia.org/wiki/996_working_hour_system) in pursuit of balanced work-life relationship. Sshwifty wouldn't exist if its author must work such extreme hours. If you're benefiting from hobbyist projects like this one, please consider to support the action."
    }`

running it via docker/portainer:
`services:
    sshwifty:
        image: niruix/sshwifty:latest
        container_name: sshwifty

        restart: always
        ports:
            - 8182:8182
        volumes:
            - /home/docker/sshwifty/config:/etc
        environment:
            #- PUID=1000 # Enter the UID of the user who should own the files here
            #- PGID=1000  # Enter the GID of the user who should own the files here
            - TZ=Australia/Sydney
            - SSHWIFTY_CONFIG=/etc/sshwifty.conf.json`

**Comment by nirui** [comment]
Hi @shezxx,

Your configuration looked fine.

`unexpected EOF` usually indicates that a external factor is terminating the connection. Can you test the setup again on local environment where you can control the variables? This may help narrow down the cause.
