### ISSUE TITLE
Unable to connect to the Sshwifty backend server: TypeError: Cannot read properties of undefined (reading 'importKey')

### ISSUE THREAD

**Issue by PrzemekSkw** [nirui/sshwifty#124]
Hello, I install Sshwifty with docker. I try in my local network over http and have issue like in title.
Logs shows:
```
[INF] Mon, 30 Jan 2023 16:59:10 UTC Sshwifty > Server (0.0.0.0:8182) > Client (172.17.0.1:40788): Request completed: /sshwifty/socket/verify
[WRN] Mon, 30 Jan 2023 16:59:10 UTC Sshwifty > Server (0.0.0.0:8182) > Client (172.17.0.1:40774): Request ended with error: /sshwifty/socket: websocket: close 1005 (no status)
```

Regards

**Comment by nirui** [comment]
This is related to web browser restrictions, see https://github.com/nirui/sshwifty#why-i-got-error-typeerror-cannot-read-property-importkey-of-undefined

In short, unless you can access Sshwifty via local address (such as `http://localhost`, `http://127.0.0.1` or similar), you must setup HTTPS for it.

**Comment by PrzemekSkw** [comment]
Hi, @nirui  thanks for answer. Can I add sshwifty as subfolder in my domain in Nginx Proxy Manager?
Regards

**Comment by nirui** [comment]
> Hi, @nirui thanks for answer. Can I add sshwifty as subfolder in my domain in Nginx Proxy Manager? Regards

The answer is ... like ... right under the section that I've linked in my previous reply, see: https://github.com/nirui/sshwifty#can-i-serve-sshwifty-under-a-subpath-such-as-httpsmydomainssh :D

This is easy money if I get paid for doing tech support :DDD

**Comment by PrzemekSkw** [comment]
OK, thanks for help.

**Comment by fanthos** [comment]
WebCrypto can works in non-ssl if I add polyfile.
Just add asmcrypto and webcrypto-liner and it should work.
```
[
"https://unpkg.com/asmcrypto.js@2.3.2/asmcrypto.all.es5.js",
"https://unpkg.com/webcrypto-liner@1.4.3/build/webcrypto-liner.shim.js",
].map(x => {
let el = document.createElement('script');
el.src = x;
document.body.appendChild(el);
})
```

**Comment by nirui** [comment]
@fanthos That's one way to get around the browser restrictions. However, most people should still just setup a HTTPS scheme instead, as it protects your data fully. Polyfilling Web Crypto while work for this specific case, don't really offer protection against many other attacks (code injection, for example).
