### ISSUE TITLE
Where is the place that takes in a sent command and sends it through SSH

### ISSUE THREAD

**Issue by CJendantix** [nirui/sshwifty#128]
I'm not 100% familiar with the api you use, nor your codebase, so I was wondering if you could guide me to the place that actually sends the command with ssh.

**Comment by nirui** [comment]
Hello,

At the client-side, the user input is handled by [`sendData`] function. However, fiddling with the inner workings of the software without understanding the whole is not recommended, and unnecessary if you were trying to fix #107, as it requires a completely different mechanism which Sshwifty don't currently support (i.e. changing how `sendData` works will not help with that).

[`sendData`]: https://github.com/nirui/sshwifty/blob/1068d22f4bfc247920d6b97b9bf256c4ee393ea6/ui/commands/ssh.js#L205

Also, this is a little bit awkward but I still wanted to say, a pull request (#122) don't make you my slave, you are **not** forced to do any of this. So :)

(Well, actually, no amount of pull requests makes anybody a slave. Just so we are clear)

**Comment by CJendantix** [comment]
Thanks lol
