### ISSUE TITLE
README中的配置文件格式错误

### ISSUE THREAD

**Issue by ReddotCleaner** [nirui/sshwifty#132]
项目主页readme中配置文件范例倒数第二行中
`OnlyAllowPresetRemotes: false` 不符合json语法，
正确格式应为 `"OnlyAllowPresetRemotes": false` 。
`sshwifty.conf.example.json`中的格式正确的，只有readme中的格式是错误的，很好用的项目，希望修正这个小错误。

**Comment by nirui** [comment]
已经遵照你的建议进行了变更，感谢。
