### ISSUE TITLE
能否支持vercel部署

### ISSUE THREAD

**Issue by lmpker** [nirui/sshwifty#133]
如题，几台机器线路都不咋好，套了cloudflare还是拉垮，vercel虽说域名被墙，但是IP还是可以用，且自动分配的ip延迟都还不错，ssh延迟高的话还是挺让人恼火的，大佬有时间的话可以研究下，不麻烦的话，建议支持vercel，感谢!

**Comment by nirui** [comment]
抱歉，云平台太多了，每个用户都会有自己所倾爱的平台，而各平台的规格以及也不一样，所以目前还是不考虑了。还是建议你下载源代码后按照平台需求自行部署。

**Comment by lmpker** [comment]
好的，感谢大佬回复，我研究研究试下
