### ISSUE TITLE
Font size up and down seems to increase text spacing more than size

### ISSUE THREAD

**Issue by CJendantix** [nirui/sshwifty#134]
When you bring it to the maximum and minimum everything looks real weird because it's increasing spacing more than size.

**Comment by CJendantix** [comment]
This doesn't look fixable because it seems that you are just calling some sort of default font size up. I will try to change the font in my build to see if that fixes it

**Comment by nirui** [comment]
Sorry for the bothering. This might be a upstream issue related to xtermjs, I'll take a look before posting any follow ups. But I'm kind busy recently, it might happen in a few days or so.

**Comment by CJendantix** [comment]
alright!

**Comment by nirui** [comment]
Hi @CJendantix, this is indeed [an upstream issue], and has been fixed in the next version (5.2.0) of xterm.js.

However, xterm.js 5.2.0 hasn't been released yet, so we'll have to wait in the meantime.

[an upstream issue]: https://github.com/xtermjs/xterm.js/issues/4474

**Comment by CJendantix** [comment]
Thank you! Just make sure to update this to xterm.js 5.2.0 asap when it releases please!

**Comment by nirui** [comment]
Sshwifty 0.2.35 has been released which fixed the problem mentioned in this issue.

https://github.com/nirui/sshwifty/releases/tag/0.2.35-beta-release-prebuild
