### ISSUE TITLE
Suggestions for optimizing web terminals

### ISSUE THREAD

**Issue by liangyoufeng** [nirui/sshwifty#136]
Can we add file upload and download functions when using web terminals?
Furthermore, it would be even better if users could freely choose terminal color schemes. We also hope to achieve automatic copying by double clicking with the mouse in web terminals, and pasting or function menu bar with the right mouse button.

**Comment by nirui** [comment]
We could have it, but I'm just too busy to actually add the functionality in. I must finish a couple of things beforehand, then anything meaningful to Sshwifty can start. Sorry :(
