### ISSUE TITLE
PSA: Link and references that points to 996icu/996.ICU repository will be removed

### ISSUE THREAD

**Issue by nirui** [nirui/sshwifty#137]
This is a PSA from the author of Sshwifty:

As you may have noticed, the home page of Sshwifty currently displays a message to show my support to the [996icu/996.ICU] project. At that time, as a programmer myself, I feel the responsibility of speaking out for my fellow IT workers for their long deserved and delayed labor rights.

However, after many years of silence, [a new development] related to the [996icu/996.ICU] project has came out of the dust recently. In short, according to the police and/or National Security Bureau of China, the owner(s) of the [996icu/996.ICU] repository had some dealings with the "foreign hostile forces", and now they're in prison.

I know, you might have suspicions towards the bureau as they... to put it lightly... usually don't carry the best intention in their minds. However, the evidence presented in the verdict is quite clear and detailed. They did some heavy jobs there. So, before someone else provides better counter evidence, I'll use the one provided by the bureau, and make my judgement accordingly.

Under this new development, I'm no longer feeling comfortable in keeping the message. Labor rights is one thing (and should still be pursued), foreign intervention is another. Like it or hate it, as a Chinese myself, I do need a stable China for her social services (security, health etc).

Plus, I can be very pissed (and vengeful, really) towards people who deceived me. For one, they should've clearly stated the fact that they were NGO members, not individuals. They're not been honest there, and I'm not happy.

Another funny thing is, these guys basically abandoned the repository after just few weeks, leaving people who needed the help hanging without help. That's... not how you helping people for real, you know? So... maybe indeed they don't really want to help (and the whole operation was nothing more than just a sabotage)???

All and all, I've decided to remove the message from file [home.vue]. And I'm writing this to let you know why. As always, if you want to keep the message, just do a fork.

This change will take effect in later versions of Sshwifty.

[996icu/996.ICU]: https://github.com/996icu/996.ICU
[a new development]: https://github.com/996icu/996.ICU/pull/26101
[home.vue]: https://github.com/nirui/sshwifty/blob/43295af6e0804e0654aa45a1c45a7100b9f19868/ui/home.vue#L90

**Comment by haodave** [comment]
Stable of Cina... You make me laugh 🥹

**Comment by lwd-temp** [comment]
It's a rumour. See https://github.com/996icu/996.ICU/commit/3af031b3308c2d213060f9a42419ddfaa215abb3

**Comment by nirui** [comment]
> It's a rumour. See [996icu/996.ICU@3af031b](https://github.com/996icu/996.ICU/commit/3af031b3308c2d213060f9a42419ddfaa215abb3)

Thanks for the update, @lwd-temp. 

I also noticed that user @996icu has archived the repository, making it read-only, so I like to know what he/she thinks about the future direction of the 996icu project. He/she can contact me via email listed here: https://nirui.org/contact

Also, I'm still open to revert the change before the next version releases, that's a little over 2 weeks away, so plenty of time for me to listen to the updates related to the event.
