### ISSUE TITLE
Malformed module path "crypto/ecdh"

### ISSUE THREAD

**Issue by Capelinha** [nirui/sshwifty#142]
Hello, I'm trying to compile from code but I'm having the following error, can you help me? I don't have much experience in GO

```
WARNING in webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

webpack 5.88.2 compiled with 4 warnings in 11919 ms
go: finding golang.org/x/net v0.14.0
go: finding github.com/gorilla/websocket v1.5.0
go: finding golang.org/x/crypto v0.12.0
build github.com/nirui/sshwifty: cannot load crypto/ecdh: malformed module path "crypto/ecdh": missing dot in first path element
```

Output of "go version" command: go version go1.13.6 linux/amd64

**Comment by nirui** [comment]
Hi, sorry for the delay.

As you might have already figured out, `crypto/ecdh` is only available after go version [`1.20`]. You need to update your Go compiler to at least version `1.20` in order to compile the code.

[`1.20`]: https://pkg.go.dev/crypto/ecdh?tab=versions

Hope it helped :)
