### ISSUE TITLE
When I use it on cellphone browser, everytime switch back to sshwifty page, it recovers to choose telnet/ssh page

### ISSUE THREAD

**Issue by crazypeace** [nirui/sshwifty#146]
Step1 Open sshwifty, click "SSH".
Step2 Paste IP, input username, click "connect"
Step3 Click "yes" for fingerprint
Step4 Switch to note app to copy the password
Step5 Switch back to browser, I want to paste the password, but it recovers to choose telnet/ssh page

https://github.com/nirui/sshwifty/assets/665889/db33292c-e4e8-4bcc-8acd-6d25bb2d8af3

**Comment by nirui** [comment]
Sshwifty is a web application, if the web browser decides to cut down the connection, there is very little we can do.

One idea is to resume the connection automatically when user comes back, but that will not happen in the short term as it require some dramatic protocol changes.

We have to live with that for now, sorry.

**Comment by nirui** [comment]
Hi, sorry for bothering you again. The demo that you uploaded contains some information which should normally be considered as secrets. I want to let you aware of this, and if you indeed need any assistance in removing those information (i.e. deleting this issue), feel free to ping me back.

**Comment by nirui** [comment]
You know what, since I received no confirmation to act in either way, I'll delete this issue which is the safest option in reducing the exposure of the secrets.

If my decision was a mistake, please re-submit them again. Sorry for the trouble.
