### ISSUE TITLE
Authentication 选择 Password 被识别为 None

### ISSUE THREAD

**Issue by nibazshab** [nirui/sshwifty#148]
ssh 连接时，在 Authentication 那三个里，选择 `Password` 不会出现输入密码的框，然后就会出现如下提示，和选择 `None` 的效果是一样的

```
Connection failed
ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
```

而选择 `Private Key` 则一切正常，会出现选择密钥的文件选项

**Comment by nirui** [comment]
可能是因为服务器上没有打开Password验证模式而导致的，你可以在`/etc/ssh/sshd_config`里打开试试。

SSH握手的时候客户端会出示可用的验证方式。如果你在Sshwifty里选择了Password，Sshwifty在握手的时候就会出示（且仅会出示）Password这个验证方式。SSHd接收客户端的握手之后，会根据自身所启用的验证方式以及客户端所提供的验证方式，在两者的交集里进行登录验证。当这个交集里没有可用验证方式时，就会出现上面的错误。

注意：一般SSHd中有两种验证方式允许你通过输入密码的方式进行登录，一种是Password，还有一种叫Keyboard-Interative。Sshwifty目前还不支持Keyboard-Interative。

**Comment by nibazshab** [comment]
原来如此，我这里是用的 Keyboard-Interative 登陆，望尽快支持，感谢

**Comment by suqianstone2023** [comment]
是这样的 比如 freebsd  的sshd验证方式就是Keyboard-Interative
