### ISSUE TITLE
有没有可能开发这样的功能

### ISSUE THREAD

**Issue by suqianstone2023** [nirui/sshwifty#149]
采用https://sshwifty-server/ssh/xxxip/xxxport 这样的方式实现点击链接弹出窗口进行ssh. telnet连接设备。或者是能传递参数过来的方式。

**Comment by nirui** [comment]
你好，你可以在"Connected Before"列表中生成这些链接。

[演示](https://github.com/nirui/sshwifty/assets/30656734/908f82f9-cf60-4b54-9bf6-feecefeb6bdb)

**Comment by suqianstone2023** [comment]
感谢！

**Comment by crazypeace** [comment]
不能传密码.
