### ISSUE TITLE
Cannot be used with Microsoft Edge

### ISSUE THREAD

**Issue by fu-sen** [nirui/sshwifty#15]
My BBS buddies tried sshwifty and found this.
He did not use GitHub, so I issued an issue on my behalf.

When you select Telnet or SSH from sshwifty in Microsoft Edge,
the following screen appears and you cannot use it:
![スクリーンショット 2020-01-29 10 40 54](https://user-images.githubusercontent.com/5434159/73320881-214c8280-4284-11ea-9d20-8294ebd8af1d.jpg)

サイトからのメッセージ = Message from site

In addition, when using Internet Explorer, it stops at the boot screen,
but I think that this need not be considered.
But Edge support will need to be considered for Windows users.

**Comment by niruix** [comment]
Can you ask your buddy to upgrade their web browser to maybe the newest one which based on WebKit? 

If the web browser does not support `TextEncoder` (Which is introduced more than 5 years ago), then it probably won't support many other APIs Sshwifty requires.

**Comment by fu-sen** [comment]
Yes. Because my main browser is Chrome. I can understand.
Looking at what it doesn't support right now, it won't be easy.
(Especially if you are using Mac or Linux)

Some may have the same opinion. This issue may need to be left open.
When closed, the same issue may come later.

**Comment by niruix** [comment]
It's not just not easy, it's basically impossible. 

Sshwifty uses many JavaScript APIs which is not exist in Internet Exporter and Edge, and there are no replacement (polyfill) for many of those APIs.

The web development has moved a long way during these 5 years, keep the web browser updated is the only way out. 

Also, a side note: Old web browser are insecure, especially when it comes to Internet Explorer. I'd personally recommend everybody to upgrade to a new one as soon as possible for ones own online safety.

**Comment by nirui** [comment]
Hello,

You probably forgot about this, but it's been a year since this issue was first published. During the year, the upgrades (third-party components mainly, which is out of my control) received by this software made it impossible to support IE and old Edges.

So sorry about that. I hope you have convinced your user to upgrade to newer version of browsers, it will be beneficial for them anyway :)

**Comment by fu-sen** [comment]
Yes, Edge is now based on Chromium. So if you care about how it works in Chrome, you can naturally expect the new Edge to look almost the same. You don't have to worry about older browsers.
