### ISSUE TITLE
can I generate address with ID, IP address for the direct connect 

### ISSUE THREAD

**Issue by limhunjung** [nirui/sshwifty#155]
thanks for the good solution. 

I'd like use the sshwifty for the customer service. 

can I generate URL for the direct connect  : eg. https://sshwifty-demo.nirui.org/user_ID@123.232.232.22

**Comment by nirui** [comment]
Hi, glad you like the project.

Have you tried the link feature? It will generate link like this: https://sshwifty-demo.nirui.org/#+Telnet:telehack.com%7Cutf-8

However, for SSH, user must manually type in login information. This is for security concerns.

You can generate links on the "Known Remote" tab.
