### ISSUE TITLE
Remote font error on Edge browser

### ISSUE THREAD

**Issue by LionCityGaming** [nirui/sshwifty#159]
![sshwifty_error](https://github.com/nirui/sshwifty/assets/72677307/63a9de53-02e1-472e-a108-7000f28fc683)

As above. The error only appears when using Edge browser (tested with Firefox, Thorium and Chrome - no errors)

**Comment by nirui** [comment]
Hi.

Please try reload the page, and see if the problem persisted.

The error might occur when the remote font failed to load within a per-determined time limit. Under normal situation, the font is still being loaded, just taking a longer time than expected, causing Sshwifty to use fallback fonts (and display that warning message to notify the user). The warning should disappear after the font is loaded.

**Comment by LionCityGaming** [comment]
> Hi.
> 
> Please try reload the page, and see if the problem persisted.
> 
> The error might occur when the remote font failed to load within a per-determined time limit. Under normal situation, the font is still being loaded, just taking a longer time than expected, causing Sshwifty to use fallback fonts (and display that warning message to notify the user). The warning should disappear after the font is loaded.

Unfortunately that doesn't work. It persists, and appears every single time I log into my SSH target. Again, every other browser works fine, just Edge strangely.

**Comment by nirui** [comment]
Maybe it's the WebGLAddon for xterm.js that is causing this problem.

Can you privide the version of your Edge browser and OS? I tested one that I have but that one don't seemed to trigger the error.

Thanks!

**Comment by LionCityGaming** [comment]
> Maybe it's the WebGLAddon for xterm.js that is causing this problem.
> 
> Can you privide the version of your Edge browser and OS? I tested one that I have but that one don't seemed to trigger the error.
> 
> Thanks!

Microsoft Edge Version 120.0.2210.121 (Official build) (64-bit)
Microsoft Windows 11 Version 23H2 Build 22631.2861

**Comment by LionCityGaming** [comment]
Update: Error does NOT appear on
**Microsoft Edge**
Version 122.0.2325.0 (Official build) canary (64-bit)

**Comment by nirui** [comment]
Edge is probably still trying to implement WebGL related features. 

Regardless, I will still fix my part of the issue. But it might take a few days since I need to setup a Windows 11 environment first. I'll keep you posted if any update on this is available.

Thanks again for reporting.

**Comment by nirui** [comment]
Hi, I've released version 0.3.6-beta, which should address this problem.

I'll close this issue for now, if the problem still occurs for you, please reopen it and report back. Thanks!
