### ISSUE TITLE
Connecting to the Local Host

### ISSUE THREAD

**Issue by cfwl1111** [nirui/sshwifty#160]
Can I connect to SSH via a loopback address from a server that has sshwifty deployed?

**Comment by nirui** [comment]
By default Sshwifty don't restrict outgoings. Through, if Sshwifty is running inside a Docker, the situation could be a little bit trickier, as Docker container uses it's own virtual network (If you found yourself under such situation, try use `host.docker.internal` as it maps to the host IP).

If you need to block Sshwifty from accessing loopbacks when Sshwifty is running as a not-containerized application, try run Sshwifty under a dedicated user, and use `iptables` to restrict which IP and port the user can connect to (i.e. `iptables -I OUTPUT -m owner --uid-owner USERNAME`).
