### ISSUE TITLE
Terminal optimization suggestions

### ISSUE THREAD

**Issue by liangyoufeng** [nirui/sshwifty#164]
Hello, the characters displayed on the terminal are overcrowded. The top, bottom, left, and right margins should be able to be adjusted back a bit. Is there a custom solution available? Or will the Docker image package be updated and modified later? Thanks！

**Comment by nirui** [comment]
Hi, can you share a screenshot to demonstrate the problem? And the web browser used when the problem occurred?

One of the dependencies that Sshwify built on made a change few months back that messed up font rendering when a custom font is used. As a result, I have to setup a fixed value to make it work. Maybe my value is wrong for some situations.

Thanks in advance.

**Comment by liangyoufeng** [comment]
![20240424173607](https://github.com/nirui/sshwifty/assets/42968364/d9f123ed-4303-40b0-ac9b-ba5f138e417c)

From the image, it can be seen that the characters are quite compact, and the margins have already been pasted to the innermost part, which is not a good thing for developers.

**Comment by liangyoufeng** [comment]
I think it'sI great. Thank you for optimizing this issue. Thank you!
