### ISSUE TITLE
[help] 如何在不同的网络环境中获取不同的ssh连接,不和sshwifty容器在同一个网络中 可以用反向代理完成这个功能么？

### ISSUE THREAD

**Issue by Goend** [nirui/sshwifty#167]

**Comment by Goend** [comment]
前提: sshwifty可以被所有的机器访问到,但sshwifty不能直接连接到所有的机器(私网环境)
这种情况下 如何保持私网环境中也可以使用sshwifty连接到对应机器呢？

**Comment by nirui** [comment]
你好，

Sshwifty使用的是操作系统提供的默认路由。如果运行Sshwifty的系统无法访问目标SSH主机，那么Sshwifty也肯定不能。

但是Sshwifty支持[SOCKS5出站]。如果可能的话，你可以试试在网络上能够访问所有对应SSH主机的位置部署一个SOCKS5代理服务器，然后让Sshwifty通过那个代理去进行连接。

[SOCKS5出站]: https://github.com/nirui/sshwifty/blob/7ea1475a162e03037fa3e0e77a7af699d701f073/sshwifty.conf.example.json#L5

**Comment by Goend** [comment]
好的 了解了 谢谢
