### ISSUE TITLE
[建议]私钥存入localStorage

### ISSUE THREAD

**Issue by countree103103** [nirui/sshwifty#31]
私钥信息在第一次读取之后,询问用户是否保存,若保存则存入localStorage,这样可以不用每次都在文件列表里找私钥了..请问能否实现呢?

**Comment by nirui** [comment]
这是故意设计成那样的，详见 #3。 

直到目前为止我还是认为浏览器的localStorage不够安全，各种插件可以偷偷读取其中（以及浏览器中其他地方）的数据。

因此我不觉得存敏感数据进去是一个好主意。而且localStorage中的数据是长期存在的，这加重了数据泄露的风险。
