### ISSUE TITLE
Non-standard Host Address?

### ISSUE THREAD

**Issue by jarbro** [nirui/sshwifty#32]
Love the app - is there a way to remove the hostname validation?

I proxy some of my ssh traffic and require a hostname of user@targethost@proxyhost - how can I disable hostname checking?

Thanks!

**Comment by nirui** [comment]
Greetings,

Currently there is no way for an user to change the validation behavior. However, I must admit that the current verification method for hostname is too restrict for it's own good, I will adjust that in the next version.

In the meantime, you might want to use IP address instead. I'll let you know once the adjustment is completed&released.

**Comment by nirui** [comment]
Hello, sorry for the delay.

The host name verifier in `0.2.7-beta` should stop causing you trouble now. Sorry for the inconvenience prior to the fix.

I'll close this issue for now, feel free to re-open it if the fix did not work as you expected.

**Comment by jarbro** [comment]
Just deployed and works great- thanks for the update!
