### ISSUE TITLE
To use Websocket interface, a valid Auth Key must be provided

### ISSUE THREAD

**Issue by qisikai** [nirui/sshwifty#33]

**Comment by qisikai** [comment]
![Uploading image.png…]()

**Comment by qisikai** [comment]
![image](https://user-images.githubusercontent.com/14859076/98491465-e1351a00-226f-11eb-99b8-56ebb0e0aa95.png)

**Comment by nirui** [comment]
So ... May I assume that you have figured it out by yourself? 🌝
