### ISSUE TITLE
Can't build or run successful

### ISSUE THREAD

**Issue by wang1** [nirui/sshwifty#35]
Hi, it's great!
When i run `npm run build` or `npm run dev`, there is a error - `go: github.com/gorilla/websocket@v1.4.2: Get "https://proxy.golang.org/github.com/gorilla/websocket/@v/v1.4.2.mod" : connect: timeout or network is unreachble`.
Because of GFW in China,  i use proxychain. But yet to OK.
Thank you for your replay.

**Comment by nirui** [comment]
Maybe you can try what I did in the [Dockerfile](https://github.com/nirui/sshwifty/blob/2a9aab8d633eb61282487aa4276d5e38d09b5b32/Dockerfile#L14). But I'm afraid this is the only help that I can provide on the issue. I don't really know how to fix individual proxies 🌝

**Comment by wang1** [comment]
Thanks a lot for nirui's tips.
It's solved by setting go's proxy. Running `go env -w GOPROXY=https://mirrors.aliyun.com/goproxy/,direct` is OK.
Thanks again.
