### ISSUE TITLE
资源路径能否改成相对路径？

### ISSUE THREAD

**Issue by e7** [nirui/sshwifty#37]
css、js这些资源在nginx反代之后是访问的是绝对路径，虽说nginx的rewrite可以解决，但不熟正则的话得搞个半天

**Comment by nirui** [comment]
抱歉了，就目前的实现方式而言，即使做出努力让Sshwifty去支持可配置的BaseURL，最终的结果不但对用户而言得益不大，同时还降低了安全性并提高了代码的维护成本。所以就当前的情况而言，项目大概不会做出这些努力了。

如果你需要将Sshwifty部署到二级目录，同时不想使用rewrite，那么可以考虑通过修改源代码并重新构建的方式来完成。Sshwifty的前端资源和后端的借口都有`/sshwifty`的前缀，你可以在代码里搜索并替换这些前缀来将他们更改到你想要的目录名。

**Comment by e7** [comment]
好的感谢！
