### ISSUE TITLE
[功能请求]将历史连接过的主机信息保存在云端

### ISSUE THREAD

**Issue by MasterOfStar** [nirui/sshwifty#38]
希望能有个[可选择项]将历史连接过的主机信息保存在云端而非cookie
就个人使用而言的话，这样相对会更方便一些，并且安全性也不会有过大的损失。

**Comment by nirui** [comment]
你可以使用导出功能将连结果的历史导出到文件上并放在自己的网络储存上同步，然后再在要使用Sshwifty的计算机上重新导入。你可以在“Known remotes”的最下方找到导入和导出功能。
