### ISSUE TITLE
Unable to verify when using nginx reverse proxy

### ISSUE THREAD

**Issue by XZB-1248** [nirui/sshwifty#43]
**Hi, nirui, I updated sshwifty few days ago,
but after that, I found that it alaways says that "Authentication has failed with provided Auth Key", 
even though the password is correct.**

![ScreenCapture2](https://user-images.githubusercontent.com/28593573/112471020-554b0700-8da6-11eb-86e7-29b6a31bc02f.png)
![ScreenCapture3](https://user-images.githubusercontent.com/28593573/112471038-5e3bd880-8da6-11eb-95a9-244a489b0f94.png)

this is my sshwifty config:
![ScreenCapture1](https://user-images.githubusercontent.com/28593573/112470268-6e9f8380-8da5-11eb-8c78-8a2fdc82aec2.png)

and this is my nginx config:
`
server
{
    listen 80;
    listen 443 ssl http2;
    underscores_in_headers on;
    index index.php index.html index.htm;
    root /www/wwwroot/XZB;

    if ($server_port !~ 443){
      rewrite ^(/.*)$ https://$host$1 permanent;
    }
    ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    ssl_certificate    /www/server/fullchain.pem;
    ssl_certificate_key    /www/server/privkey.pem;
    error_page 497  https://$host$request_uri;

    add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";

    location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
    {
      expires      30d;
      error_log off;
    }

    location ~ .*\.(js|css)?$
    {
      expires      12h;
      error_log off;
    }

    location ^~ /
    {
      proxy_pass http://127.0.0.1:8080/;
      proxy_http_version 1.1;
      proxy_set_header Connection "upgrade";
      proxy_set_header Upgrade $http_upgrade;
    }

    access_log /dev/null; 
    error_log  /dev/null;
}
`

**Comment by nirui** [comment]
I've changed how password is authenticated in the last version, which includes modification for both frontend(the web interface) and the backend code.

Maybe the web browser is still using cached old frontend program from the previous version.

Can you reload the page (via Ctrl+F5 to force cache reload) to see if it comes back to normal?

**Comment by XZB-1248** [comment]
> I've changed how password is authenticated in the last version, which includes modification for both frontend(the web interface) and the backend code.
> 
> Maybe the web browser is still using cached old frontend program from the previous version.
> 
> Can you reload the page (via Ctrl+F5 or Ctrl+Shift+R to force cache reload) to see if it comes back to normal?

Of course I tried that.
Before I open this issue, I even tried to disable cache in dev tools and reload in InPrivate window.
But the error was still there, it doesn't work at all.

![ScreenCapture](https://user-images.githubusercontent.com/28593573/112483637-2f2c6380-8db4-11eb-8e6c-826d83132601.png)

**Comment by nirui** [comment]
That's weird. Based on the screenshot, your web browser is still trying to load the old frontend assets.

I knew that because I changed how the name of the assets is generated in the lastest version. The new version does not include the number prefix (0.xxxxx.js, 1.xxxxx.js etc) in their names.

I think the Nginx or some other (CDN) servers down the line might have cached the `/` file (The homepage file). 

So, to begin, can you take look cache related settings? Maybe try to manually release the cache for `/`.

**Comment by XZB-1248** [comment]
> That's weird. Based on the screenshot, your web browser is still trying to load the old frontend assets.
> 
> I knew that because I changed how the name of the assets is generated in the lastest version. The new version does not include the number prefix (0.xxxxx.js, 1.xxxxx.js etc) in their names.
> 
> I think the Nginx or some other (CDN) servers down the line might have cached the `/` file (The homepage file).
> 
> So, to begin, can you take a look at cache related settings? Maybe try to manually release the cache for `/`.

Ohhhh. It works!!!
I added "proxy_cache off;"

Thx for Ur help😎😎😎

**Comment by nirui** [comment]
Glad that I've helped.

I just have to change the authentication method so I can deploy Sshwifty on my cluster without giving myself a headache. Sorry for the inconvenience and frustration 😆

**Comment by XZB-1248** [comment]
> Glad that I've helped.
> 
> I just have to change the authentication method so I can deploy Sshwifty on my cluster without giving myself a headache. Sorry for the inconvenience and frustration 😆

😂😂😂That doesn't matter, it didn't waste time.
Sooner or later, there will be similar problems.
