### ISSUE TITLE
Default font size?

### ISSUE THREAD

**Issue by binarydad** [nirui/sshwifty#44]
I love this project! Is there any way to change the default font size? I find it to be too big. Thanks!

**Comment by nirui** [comment]
Sorry, currently there is no way to change the UI front size (other than the browser Ctrl++/Ctrl+- zoom).

However, you can change the size of the console text via the console tool bar. The tool bar can be accessed by click the currently opened tab label. It's not "default size" though, as you have to re-adjust the front size everytime when a new console is opened.

**Comment by hzxie** [comment]
need this feature +1
