### ISSUE TITLE
Heroku restarts

### ISSUE THREAD

**Issue by capriciousduck** [nirui/sshwifty#47]
What if heroku cycling occurs when I use the app?. By the way I ping the app every 5 minutes to prevent dyno sleeping.

**Comment by nirui** [comment]
Hi. I did not receive the notification for the issue, sorry for the late reply.

Heroku will kill the application if it detects no "traffic" in their frontend router. They documented it in their free-tier spec as "Sleeps after 30 mins of inactivity". And their frontend router only clear the sleep timer when it receives new HTTP requests, not traffic on already established active Websocket connections.

I could make Sshwifty to periodically send HTTP requests to the backend to trick Heroku to reset their sleep timer, however, this solution feel like cheating and Heroku-specific. I think I need to contact Heroku customer service first before deciding what to do next, I mean, it'll be great if they could modify how the timer works.

I'll keep you posted after I figured out a solution for this.

**Comment by capriciousduck** [comment]
Ok

**Comment by nirui** [comment]
Hello, I've released 0.2.11 which implemented a HTTP ticker that sends HTTP requests periodically to keep Heroku from killing the app.

This should resolve the issue :)

**Comment by capriciousduck** [comment]
Thanks!
