### ISSUE TITLE
0.2.11 前端密码一直提示密码错误

### ISSUE THREAD

**Issue by MFYDev** [nirui/sshwifty#48]
nirui您好！

刚刚更新了0.2.11，使用的配置文件和0.2.10版本均相同，但是升级之后进入前端界面时一直提示密码错误，后端错误日志如下：

```bash
| [WRN] Fri, 30 Apr 2021 11:07:43 CST Sshwifty > Server (127.0.0.1:9858) > Client (127.0.0.1:35918): Request ended with error: /sshwifty/assets/7ff39440b9174e0f8716023d858943b7.svg: HTTP Error (404): Page not found
4|sshwifty | [WRN] Fri, 30 Apr 2021 11:07:43 CST Sshwifty > Server (127.0.0.1:9858) > Client (127.0.0.1:35916): Request ended with error: /sshwifty/socket/verify: HTTP Error (403): To use Websocket interface, a valid Auth Key must be provided
4|sshwifty | [WRN] Fri, 30 Apr 2021 11:08:10 CST Sshwifty > Server (127.0.0.1:9858) > Client (127.0.0.1:35978): Request ended with error: /sshwifty/socket/verify: HTTP Error (403): Authentication has failed with provided Auth Key
```

**Comment by nirui** [comment]
刷新一下页面（和代理服务器的）缓存试试？0.2.10到0.2.11并没有改变密码验证功能的工作方式，但是0.2.9到0.2.10时有过变更。

**Comment by MFYDev** [comment]
不好意思，前几天有些事情忙，回复晚了。

https://github.com/nirui/sshwifty/issues/40#issuecomment-802813547

我是使用的这个issue提到的相同的nginx配置，但是不知道为什么最近又突然出先了相同的情况，显示显示密码错误，后来又显示和这个issue一开始的开始界面一样。按理说正常按照这个正确的nginx不应该出现这种情况了。

后续换成了docker安装，挂载了预设值文件之后倒是不用那么多配置，只需要反向代理中加入 /websocket 的反向代理就行了，其他的倒是不用改，这样用docker倒是方便很多。

但就是不明白为什么忽然二进制安装会出现这种情况，配置都和以前0.2.9的时候一样的

**Comment by nirui** [comment]
基于现有的信息我只能猜测是缓存的原因，跟 #43 的问题类似。

在当前的版本下，Sshwifty会让浏览器去缓存首页`/`的HTML代码，缓存方式是ETag验证。这样的好处可以让用户立即打开已经缓存在本地的页面，而不需要每次重新下载首页。

在一般情况下，如果首页因为软件更新而过期，用户只需要按F5或刷新页面就能让浏览器去重新验证缓存并下载新的首页文件就好了。但是，Nginx这样的代理服务器会在某些配置下也去缓存首页的代码，这样一来用户无论怎么刷新浏览器都不能下载到最新的文件了。

如果我上面的猜测是正确的，那么在Nginx配置文件的相关位置添加`proxy_cache off;`大概就能解决问题。我这边也已经提交了 7c261232dd907b7742531d7e3c4052cf1063c339 ，让Sshwifty不再建议浏览器去缓存它的首页`/`。

当然，上面只是猜测。如果您以后再遇到这样的问题，请多提供一些信息，比如浏览器的网络请求（在浏览器控制台中），这样我可以看到更多线索。另外，你还可以试试排除法，将出问题的Sshwifty和它的配置文件下载到本地，然后在本地直接用那个配置运行/访问Sshwifty（不经过任何代理），这样可以确定是故障是本身Sshwifty造成的，还是由Nginx的配置引起。

**Comment by MFYDev** [comment]
nirui 您好，超级感谢您的细致回答！很抱歉因为一些琐事又回复晚了。

后续我并没有继续使用二进制的方法来进行部署，而是继续使用docker部署的。

docker部署与二进制部署的反向代理部分基本上是一样的，所以再后来只要能用我就没有考虑那么多。

直到今天我再次使用时发现浏览器一直提示以下错误：

![image](https://user-images.githubusercontent.com/53750381/117544641-f9d29100-b054-11eb-88b4-e460ae9a273b.png)

于是经过我自己的搜索，确实也发现在 https://github.com/nirui/sshwifty/issues/43 中已经通过向反向代理中加入您之前提到的 `proxy_cache off;` 解决了此问题。

但是我在自己的反向代理部分中加入 `proxy_cache off;` 之后，错误提示并没有消失，无论是清空缓存亦或是使用private模式，在 `https://sshwifty.domain/sshwifty/socket/verify` 永远都是403 not found 并显示以下内容：

![image](https://user-images.githubusercontent.com/53750381/117544759-71082500-b055-11eb-8764-948419621352.png)

我的反向代理配置如下：

```nginx
#PROXY-START/
location /
{
    proxy_pass http://REDACTED:9858;
    proxy_set_header Host REDACTED;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
    proxy_cache off;
}
location /sshwifty/socket {
     proxy_pass http://REDACTED:9858;
     proxy_set_header Host REDACTED;
     proxy_set_header X-Real-IP $remote_addr;
     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
     proxy_set_header X-Forwarded-Proto https;
     proxy_set_header Upgrade $http_upgrade;
     proxy_set_header Connection $connection_upgrade;
     proxy_cache off;
}
#PROXY-END/
```

Nginx 总配置如下：（基本就是宝塔自动生成的删除了一部分，总配置中引用了上述的反向代理配置，所以两个算是一个整体配置）

<details>

```nginx
map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }
    
server
{
    listen 80;
	listen 443 ssl http2;
    server_name ssh.mfy.world;
    index index.php index.html index.htm default.php default.htm default.html;
    root /www/wwwroot/ssh.mfy.world;
    
    #SSL-START SSL相关配置，请勿删除或修改下一行带注释的404规则
    #error_page 404/404.html;
    #HTTP_TO_HTTPS_START
    if ($server_port !~ 443){
        rewrite ^(/.*)$ https://$host$1 permanent;
    }
    #HTTP_TO_HTTPS_END
    ssl_certificate    /www/server/panel/vhost/cert/ssh.mfy.world/fullchain.pem;
    ssl_certificate_key    /www/server/panel/vhost/cert/ssh.mfy.world/privkey.pem;
    ssl_protocols TLSv1.1 TLSv1.2;
    ssl_ciphers EECDH+CHACHA20:EECDH+CHACHA20-draft:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    add_header Strict-Transport-Security "max-age=31536000";
    error_page 497  https://$host$request_uri;

    #SSL-END
    
    #ERROR-PAGE-START  错误页配置，可以注释、删除或修改
    #error_page 404 /404.html;
    #error_page 502 /502.html;
    #ERROR-PAGE-END
    
    #PHP-INFO-START  PHP引用配置，可以注释或修改

	#引用反向代理规则，注释后配置的反向代理将无效
	include /www/server/panel/vhost/nginx/proxy/ssh.mfy.world/*.conf;

	include enable-php-00.conf;
    #PHP-INFO-END
    
    #REWRITE-START URL重写规则引用,修改后将导致面板设置的伪静态规则失效
    include /www/server/panel/vhost/rewrite/ssh.mfy.world.conf;
    #REWRITE-END
    
    
    #一键申请SSL证书验证目录相关设置
    location ~ \.well-known{
        allow all;
    }
    
    access_log  /www/wwwlogs/ssh.mfy.world.log;
    error_log  /www/wwwlogs/ssh.mfy.world.error.log;
}
```

</details>

虽然此错误不影响使用，但是我不是很清楚为什么会出现这个错误，以及该如何解决呢？

期待您的解答，感谢，辛苦了！

**Comment by nirui** [comment]
Sshwifty会在你打开页面的时候使用空密码请求一次后端，并根据返回的结果来确定是否需要显示密码输入界面。你看到的错误其实就是这次请求（叫Probing）引发的。当你输入了正确的密码之后，后端接口（即`/socket/verify`）会返回200，这样前端就会打开控制界面（主页）了。

因此，如果你只是每次打开Sshwify页面的时候遇到了这一次错误，而输入正确的密码之后能正常使用的话，`/socket/verify`的错误是可以忽略的；当然，如果你输入的密码是正确的，但仍然不能正常使用，则是真的出了问题。

另外，如果你直接访问`/socket/verify`的话，由于缺少参数，所以Sshwifty会拒绝这个请求。这也就是你直接访问那个接口后，看到红色页面的原因。

**Comment by MFYDev** [comment]
原来是这样，明白了~

非常感谢您的及时解答，那我已经没有任何其他问题了，辛苦您了！

我将关闭此issue~

**Comment by nirui** [comment]
Hi，你好。很抱歉打扰到了你。

我这边在看过往的Issue时发现你在 https://github.com/nirui/sshwifty/issues/48#issuecomment-835404597 提交的一个截图里有一个 .world 结尾的域名。而在你同一个评论里给出的配置信息中（甚至于同一张截图里），你用“REDACTED”代替了这个域名。我猜测你是想隐藏这个域名，但是忘了给截图打码。

我这边先隐藏了上述回复，这样未登陆GitHub的用户是无法查看这个域名的。如果您认为有必要的话，可以进一步删除这个回复（GitHub会保留编辑历史，所以编辑是无法除去隐私信息的）。

**Comment by MFYDev** [comment]
太感谢nirui了！已经删除了带有域名的截图！

您的为人真的太好了太感动了。。。隐藏域名也是怕会被攻击，不过倒是设置了一个很强的密码。

再次感谢您！
