### ISSUE TITLE
CTRL+Q screen console key doesn't send the correct key

### ISSUE THREAD

**Issue by daniml3** [nirui/sshwifty#52]
When pressing the CTRL+Q button, the key sent is the Q key instead of CTRL+Q, I gues that its because of ctrlKey being false on the keys list: https://github.com/nirui/sshwifty/blob/4bb90f183493f008db9a9e1db49d82b538fe2b7b/ui/widgets/screen_console_keys.js#L633

**Comment by nirui** [comment]
Confirmed. Nice catch! And I've committed fixed code to the repository. Thank you!

Are you in a hurry? I can release the next version right way so you can use the fixed version.

Sorry for the mess up.

**Comment by daniml3** [comment]
No need right now, its not something I really need but found the issue ans just reported it. Thanks for the quick fix!
