### ISSUE TITLE
Error: Cannot use encrypted Private Key file

### ISSUE THREAD

**Issue by soundghost** [nirui/sshwifty#54]
我的密钥加了密，当我在sshwifty上指定本地的加密id_rsa时，弹出这个提示。

请问可有解决的办法？

**Comment by soundghost** [comment]
我后来看到说明了，sshwifty不支持加了密的密钥。

**Comment by nirui** [comment]
是的，目前是这样设计的。这样做不是很方便，抱歉，但是这是出于安全考虑。

**Comment by soundghost** [comment]
了解了，谢谢您
