### ISSUE TITLE
Feature: Support for encrypted OpenSSH Keys 

### ISSUE THREAD

**Issue by localleon** [nirui/sshwifty#58]
Hey nirui, 

this project looks really promising and interesting. Is there any chance we could add support for encrypted SSH-Keys in the GUI? All of my keys are password encrypted and i would love to use them with this tool. Are there any reasons that speak against implementing such a feature? 

Are you interested in this feature and would be willing to accept PRs?

**Comment by nirui** [comment]
Feature wise, it's really easy to add that into the software.

**However**, there is a concern on my side. Simply put, I really don't want to collect that many private information consider this software is designed for web browsers which can sometimes be a chaotic environment. Private Key uploading is bad enough already but the software needs it to perform basic Private Key authentication. Private Key + a decrypt password? That's a whole another level of badness.

So yes, I intentionally left that feature out before I discovered a better solution.

In the meantime, I would recommend that you generate a special set of unencrypted private keys to be used specifically in Sshwifty. That way you can further bind those keys with an "(mentally) untrusted" SSH login accounts, add another layer of security.
