### ISSUE TITLE
Failure to scroll properly

### ISSUE THREAD

**Issue by MattiDragon** [nirui/sshwifty#60]
Whenever you try to scroll up or down it just spams `^[[A` or `^[[B` respectively. Is there something that can be done on my side or is this an issue in the gui? Scrolling is useful when something spits out a lot of stuff.

**Comment by nirui** [comment]
Which shell you connected to is causing the issue? Normally, a shell such as Bash will handle such input gracefully. 

And yes, it only happens to programs that does not properly handle Arrow keys (which is what scrolling will be converted to in some applications).

Here is a little background: `^[` is the prefix of an ANSI escape code,  and `[A` is a [CSI sequence] that represents "Up key pressed". A program that supports arrow keys (and scrolling) should read the sequence then execute it's corresponding actions (usually includes clearing the printed sequence representation). However, if a program does not support such sequence, it will not do anything (that will leave all the `^[[A` and ^[[B uncleared).

[CSI sequence]: https://en.wikipedia.org/wiki/ANSI_escape_code#CSI_(Control_Sequence_Introducer)_sequences
