### ISSUE TITLE
希望添加 IPv6 支持

### ISSUE THREAD

**Issue by hmsjy2017** [nirui/sshwifty#62]
IPv6 Only VPS 无法访问

**Comment by nirui** [comment]
我检查了代码，发现无法通过IPv6地址连接的问题可能是由IPv6地址解析器中的Bug导致的，我已经在 a2d99ebeef422c7bbfe43c2571c339f7595ad12c 里提交了修复，这个修复会随下一个版本发布。

Sshwifty本身是支持IPv6的，由于这个问题仅影响IPv6地址解析器，所以就目前而言，你可以使用Hostname地址的方式来绕过这个问题。简单的说就是通过域名AAAA记录来进行连接。

**Comment by nirui** [comment]
包含上述修复的版本`0.2.17-beta`已经发布，请按需更新。

我这边先将这个Issue关闭，如果相关修复并没有达到你的预期，可以将Issue重新打开。

**Comment by hmsjy2017** [comment]
可以访问了，不过`ListenInterface`字段必须填写公网 IPv6 地址（::1也不行），否则无法访问。

**Comment by nirui** [comment]
`ListenInterface`定义的是Sshwifty的监听接口，不会影响出站连接。你的意思是当`ListenInterface`的值被设定成`::1`之后Sshwifty本身无法访问么？我这边没有复现这种状况。我的步骤是：

1. 编辑`sshwifty.conf.example.json`，设置`"ListenInterface": "::1",`
2. 运行`SSHWIFTY_CONFIG=./sshwifty.conf.example.json ./sshwifty`
3. 在运行Sshwifty的机器上，运行`curl -v [::1]:8182 -o /dev/null`，得到HTTP 200：

        $ curl -v [::1]:8182 -o /dev/null
        *   Trying ::1:8182...
        * TCP_NODELAY set
          % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                         Dload  Upload   Total   Spent    Left  Speed
          0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to ::1 (::1) port 8182 (#0)
        > GET / HTTP/1.1
        > Host: [::1]:8182
        > User-Agent: curl/7.68.0
        > Accept: */*
        > 
        * Mark bundle as not supporting multiuse
        < HTTP/1.1 200 OK
        < Content-Length: 8627
        < Content-Type: text/html; charset=utf-8
        < Date: Sun, 07 Nov 2021 02:51:27 UTC
        < 
        { [3978 bytes data]
        100  8627  100  8627    0     0  4212k      0 --:--:-- --:--:-- --:--:-- 4212k
        * Connection #0 to host ::1 left intact

**Comment by hmsjy2017** [comment]
经测试，`ListenInterface`字段填写`::1`时，本机执行 `curl`确实能得到`HTTP 200`，但公网无法访问。

**Comment by nirui** [comment]
`::1`是Loopback地址，相当于`127.0.0.1`。如果你想在外部访问的话，应该绑定的是`::`（相当于`0.0.0.0`，即“所有接口”），而不是`::1`。

**Comment by hmsjy2017** [comment]
填写`::`后公网可以访问。👍
