### ISSUE TITLE
An app has been made for ios

### ISSUE THREAD

**Issue by 0xfff0800** [nirui/sshwifty#64]
https://github.com/0xfff0800/Parrot.Flo

**Comment by nirui** [comment]
You're welcome to maintain your own fork of Sshwifty as long as you follow the terms in the [LICENSE].

Also, it is [NOT recommended to use our demo to provide any service], as the demo service provides no guarantee what so ever.

[LICENSE]: https://github.com/nirui/sshwifty/blob/c3af1e62ee83c86ef9ced186eea781af0c135607/LICENSE.md

[NOT recommended to use our demo to provide any service]: https://github.com/0xfff0800/Parrot.Flo/blob/025e23a6fb1ec1269dec3eaba5760f2de0da6adf/URLRedirectDemo/ViewController.swift#L24

**Comment by 0xfff0800** [comment]
Thanks for reminding me of that, I'll explain to them
