### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by capriciousduck** [nirui/sshwifty#66]
Hello. I deployed this app on Heroku, and it running very smoothly! However, I have a question: Let's say I SSH-ed into a server and so it will be saved in known remotes. But what happens when the Heroku dyno restarts? Will the config be wiped? If yes, is there a way to make the config persist across reboots?

**Comment by nirui** [comment]
The record is saved in the browser on your own computer (You can export them if you needed a backup). Currently, nothing is saved on the remote site.

**Comment by capriciousduck** [comment]
Okay, great!

Thanks!
