### ISSUE TITLE
HTTP ERROR 503

### ISSUE THREAD

**Issue by Corybyte** [nirui/sshwifty#67]
服务器环境 :ubuntu20.04 

我执行了sshwifty 
[INF] Thu, 09 Dec 2021 22:01:01 CST Sshwifty: Initializing
[INF] Thu, 09 Dec 2021 22:01:01 CST Sshwifty > Configuration > Redundant: Loading configuration from one of the default configuration files ...
[INF] Thu, 09 Dec 2021 22:01:01 CST Sshwifty > Configuration > Redundant: Configuration file "/etc/sshwifty.conf.json" has been selected
[INF] Thu, 09 Dec 2021 22:01:01 CST Sshwifty > Server (127.0.0.1:8182): Serving
[INF] Thu, 09 Dec 2021 22:03:06 CST Sshwifty > Server (127.0.0.1:8182): Closed
[INF] Thu, 09 Dec 2021 22:03:06 CST Sshwifty: Closed

sshwifty.conf.example.json如下

{
  "HostName": "",
  "SharedKey": "WEB_ACCESS_PASSWORD",
  "DialTimeout": 5,
  "Socks5": "",
  "Socks5User": "",
  "Socks5Password": "",
  "Servers": [
    {
      "ListenInterface": "0.0.0.0",
      "ListenPort": 8182,
      "InitialTimeout": 3,
      "ReadTimeout": 60,
      "WriteTimeout": 60,
      "HeartbeatTimeout": 20,
      "ReadDelay": 10,
      "WriteDelay": 10,
      "TLSCertificateFile": "",
      "TLSCertificateKeyFile": ""
    }
  ],

通过IP:端口无法访问 返回HTTP ERROR 503
防火墙全开放的

**Comment by nirui** [comment]
我这边无法使用你给出的信息复现问题。

    $ cat sshwifty.conf.example.json.2
    {
    "HostName": "",
    "SharedKey": "WEB_ACCESS_PASSWORD",
    "DialTimeout": 5,
    "Socks5": "",
    "Socks5User": "",
    "Socks5Password": "",
    "Servers": [
    {
    "ListenInterface": "0.0.0.0",
    "ListenPort": 8182,
    "InitialTimeout": 3,
    "ReadTimeout": 60,
    "WriteTimeout": 60,
    "HeartbeatTimeout": 20,
    "ReadDelay": 10,
    "WriteDelay": 10,
    "TLSCertificateFile": "",
    "TLSCertificateKeyFile": ""
    }
    ],
    $ SSHWIFTY_CONFIG=./sshwifty.conf.example.json.2 ./sshwifty

    Sshwifty Web SSH Client 0.2.16-beta-release-1-ga2d99eb*

    Copyright (C) NI Rui <ranqus@gmail.com>
    https://github.com/nirui/sshwifty

    [INF] Thu, 09 Dec 2021 22:28:45 CST Sshwifty: Initializing
    [INF] Thu, 09 Dec 2021 22:28:45 CST Sshwifty > Configuration > Redundant: Loading configuration from: ./sshwifty.conf.example.json.2
    [WRN] Thu, 09 Dec 2021 22:28:45 CST Sshwifty > Configuration > Redundant: Unable to load configuration from "File": unexpected EOF
    [ERR] Thu, 09 Dec 2021 22:28:45 CST Sshwifty: "Redundant" loader cannot load configuration: All existing redundant loader has failed
    [ERR] Thu, 09 Dec 2021 22:28:45 CST Sshwifty: Unable to start due to error: All existing redundant loader has failed
    [INF] Thu, 09 Dec 2021 22:28:45 CST Sshwifty: Closed

我这边可以确认的是，你上面给出的配置文件并不是Sshwifty进程退出的原因，因为错误的配置文件格式会产生报错日志项，如上面的 “Unable to load configuration from……”。

而如果你的前置代理服务器无法连接到Sshwift的话（比如因为Sshwifty的进程退出了），是会导致HTTP 503的。你可以进一步检查相关设置。
