### ISSUE TITLE
Changing wss URL /sshwifty/socket to bypass blocking FW 

### ISSUE THREAD

**Issue by nodje** [nirui/sshwifty#73]
Hey,

I've just started to use your excellent and highly useful project.
But while it works perfectly in an open environment, some corporate firewalls are able to block it.
I can open the main page, but as soon as I click on open + SSH , I git a wss error

After a quick assessment, wss protocol works for some other websites.

I can only conclude that the FW blocks this one based on the name wss://ssh.domain.com/sshwifty/socket
Obvioulsy, choosing a subdomain different than "ssh." can only help, but I'm pretty sure the "sshwifty" string is what the FW takes its decision to block upon.

After a quick search in the code, I found this string defined in:
`ui/app.js` for the client and `application/controller/controller.go`

I'm gonna create a fork to test this, but as I'm not familiar with Go, I just wanted to have a confirmation that I could freely change the URL and that it would work.

thanks!

**Comment by nirui** [comment]
I'm not really sure. 

If it was a WSS connection, the WebSockets payload should be encapsulated completely in a TLS pipe. Which means that it is impossible for a firewall to see the content, including the "sshwifty" keyword.

Maybe it's something else?

**Comment by nodje** [comment]
hey, thanks for your answer.

All I can say is, if I connect from internet it works. 
If I connect from the corporate network, I can access the UI at `https://ssh.domain.com` but then when I click on + then SSH, the Upgrade request to wss://ssh.domain.com/sshwifty/socket fails. 
This works fine from internet as I said.
I think this behaviour can only be based on the URL string. I've validated that other wss Upgrade were working.

Anyway, i'm gonna test this and report. It's pretty easy to build the project with your Dockerfile (takes 1100s for me though!)

but I'm just unsure if the Go server structure could be dependent on the naming `sshwifty` 
(as in controller.go ```case "/sshwifty/socket":
		err = serveController(h.socketCtl, w, r, clientLogger)```
		
		
because the string `sshwifty` is everywhere, and could easily be a convention.

**Comment by nirui** [comment]
Yeah, those `/sshwifty/` strings (in both `controller.go` and `app.js`) are not designed as a long term solution. My plan is to rewrite the entire project some time in the future so it fits my standard. However, all of my free time is occupied by another of my pet project (which could benefit Sshwifty if succeed) as well as many other things.

So as of now, I think we might have to live with them ;-)

Lastly, if WebSockets Upgrade still keeps failing even after you changed `/sshwifty/socket` to something else, maybe take look the server log to see what the server has to say about the error.

**Comment by nodje** [comment]
No worries, I'll do my own tests.

Thanks for answering me during 春节, and 虎年快乐 by the way, 大吉大利 of course :)

Let us know about your new project when time is ripe.

**Comment by nodje** [comment]
Ok, changing the string makes no difference, and even though the server logs a "Request completed: /sshwifty/socket/verify" then it logs nothing upon the client websocket 1006 error. Meaning this Websocket Upgrade request doesn't reach the server and is blocked on the client side, if I'm not mistaken.

I've also tried a direct (without front reverse proxy) unencrypted, but also got a 1006 error and nothing logged on the server.

I don't know how they do it, since some WSS upgrades are working, but I have to admit the corporate security layer is more clever than I am, I have to give up!

**Comment by nirui** [comment]
WebSocket handshake starts just as any other normal `GET` requests, but with few [added headers].

[added headers]: https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers

Can you access the WebSocket interface `https://<YourSshwiftyInstance>/sshwifty/socket` directly from your browser? An error message should be displayed since the parameters required by WebSocket handshake are missing, but the error page itself should load just fine unless the corporate network is indeed blocking the said interface via URI filtration.

Just a hit if you want to debug this further ;-)

**Comment by nodje** [comment]
This works (or fails) as expected on both internet and corporate network.
The UI and generally the sshwifty instance is accessible from the corporate network.

it's just that they block the upgrade to wss protocol, or actually "just" websocket connection, except from known websites probably
