### ISSUE TITLE
ipv6无法连接

### ISSUE THREAD

**Issue by 2826915729** [nirui/sshwifty#76]
安装的是Docker
服务器是双栈的，本地也有ipv6地址，连接IPV6时提示 
`dial tcp [IPV6]:PORT: connect: network is unreachable`

搭建地址：[ssh.vpshax.ml](https://ssh.vpshax.ml) 

Nginx配置截图
![Screenshot_2022-02-06-13-14-45-177_in mfile](https://user-images.githubusercontent.com/31442507/152668711-d2a45ac9-a995-45bd-b8bd-354222c0d56a.jpg)

Docker logs
![Screenshot_2022-02-06-13-24-40-488_com sonelli juicessh](https://user-images.githubusercontent.com/31442507/152668780-97e20af1-e583-40ba-b772-fe92b1d60b02.jpg)

**Comment by nirui** [comment]
错误信息里 `[IPV6]:PORT` 所呈现的地址与你所输入的地址是一致的么？我想确定一下是不是IPv6的地址转换函数出了问题。

**Comment by 2826915729** [comment]
> 错误信息里 `[IPV6]:PORT` 所呈现的地址与你所输入的地址是一致的么？我想确定一下是不是IPv6的地址转换函数出了问题。

是一致的

**Comment by 2826915729** [comment]
![IMG_20220206_152546](https://user-images.githubusercontent.com/31442507/152671441-18d5eade-c292-45fb-af79-bb33a33e2331.jpg)
 
提示 `Connection failed

dial tcp [2a01:4f9:6a:44ef:100d:affb:7634:1]:22: connect: network is unreachable`

**Comment by nirui** [comment]
如果是这样的话，问题大概跟Sshwifty无关。

你可以试着确认一下容器内的进程是否能访问所述地址。具体来说，就是先用`docker inspect -f "{{ .State.Pid }}" <容器的名字或ID>`查到容器内主进程的PID，然后用`nsenter -t <前面得到的PID> -n ssh <用户名>@<上述地址>`试着在容器的Namespace里直接通过`ssh`来进行链接。

之后，还可以接着在Root Namespace（就是非Docker容器中的环境）里试着用`ssh`直接进行连接。如果在非Docker容器中可以连上，但在Docker里的进程不行，可能是Docker没有开启相关支持。

**Comment by 2826915729** [comment]
![image](https://user-images.githubusercontent.com/31442507/152672470-3f332a26-3afe-4728-a621-1ecaad83fd8a.png)
试了下按照你给出的操作，发现在容器的Namespace里不能进行链接

**Comment by nirui** [comment]
如果你在容器外面可以连接，但是在容器内不行的话，大概是Docker的问题。你可以参考[Docker官方文档]的说明来开启它IPv6支持，然后再自行测试一下。

[Docker官方文档]: https://docs.docker.com/config/daemon/ipv6/

我这边不知道你系统的设置和配置状态（也不太可能模拟出这些状态），所以只能给你笼统的建议，不一定准确，你可能需要自行多实验一下。

**Comment by 2826915729** [comment]
> 如果你在容器外面可以连接，但是在容器内不行的话，大概是Docker的问题。你可以参考[Docker官方文档](https://docs.docker.com/config/daemon/ipv6/)的说明来开启它IPv6支持，然后再自行测试一下。
> 
> 我这边不知道你系统的设置和配置状态（也不太可能模拟出这些状态），所以只能给你笼统的建议，不一定准确，你可能需要自行多实验一下。

ok，已经弄好了
