### ISSUE TITLE
Feature Request, Auto Login.

### ISSUE THREAD

**Issue by abrahack** [nirui/sshwifty#79]
Hello,

Firstly I want to thank you for such an amazing project.

Now I want to know is it possible to pass the login requirements as http arguments ;

Like something like this `http://localhost:8182/?username=root&password=password&host=1.1.1.1&port=22&mode=ssh` ?

I would love to hear from you soon.

Kind Regards,
@abrahack .

**Comment by nirui** [comment]
Hi!

Sorry, currently Sshwifty does not support this feature :(

Can you take look the Launch Link feature to see if it fulfills you needs? You can generate the link on the "Known Remote"  list, the link will be similarly to https://sshwifty.herokuapp.com/#+Telnet:fusen.ddns.net:55123%7Cshift-jis. But you still have to enter password/private key for SSH connections.

**Comment by abrahack** [comment]
Okay thanks for your help.
