### ISSUE TITLE
feature request: persistent connections 

### ISSUE THREAD

**Issue by kzshantonu** [nirui/sshwifty#81]
Hi, amazing work here. Is there any plans to allow persistent connections? Would be useful if someone accidentally closes a browser tab or simply wants to keep a command running without keeping browser tab open. Regards

**Comment by nirui** [comment]
Hi :D

Adding persistent connections (session resumption) requires a new internal protocol for Sshwifty, which is a long term thing. But I'll do research on this, but currently I cannot provide any promise.

In the meantime, please try `tmux`, which allow you to keep and resume a terminal session on the host even after the SSH connection is dropped.
