### ISSUE TITLE
Password protected ssh key

### ISSUE THREAD

**Issue by poudenes** [nirui/sshwifty#84]
Hi All,

great tool. My ssh key have a pharsekey to able to login. How can I let this work in SSHwifty?

**Comment by nirui** [comment]
Hi, currently Sshwifty does not support Keyboard Interactive login (see #55), can you enable `PasswordAuthentication` or `PubkeyAuthentication` on your SSH host?

**Comment by poudenes** [comment]
What I can do is create a new ssl with 4048 without pass.
