### ISSUE TITLE
允许单独使用Alt和Ctrl，而非直接输入组合键

### ISSUE THREAD

**Issue by DreamOneX** [nirui/sshwifty#85]
Linux下有不少软件（如`vim`、`bash`）会大量使用以`Ctrl`或`Alt`开头的组合键，而sshwifty只提供了**12**个以`Ctrl`开头的组合键，这与`vim`一类软件所需要的就相形见绌了，能允许单独使用`Ctrl`和`Alt`吗

**Comment by nirui** [comment]
你是在手机中使用Sshwify的么？

我一开始的时候确实测试了自定义功能键（即Modifier键保持）的实现方式，类似JuiceSSH，但是发现这么做不能为手机用户提供太多的效率提升，同时使用上还非常繁琐。

如果你有在手机上使用Sshwifty的需要，建议还是插一个蓝牙键盘，这样不但能更有效的使用SSH，还能避免由输入法引入的兼容性问题。

**Comment by DreamOneX** [comment]
> 你是在手机中使用Sshwify的么？
> 
> 我一开始的时候确实测试了自定义功能键（即Modifier键保持）的实现方式，类似JuiceSSH，但是发现这么做不能为手机用户提供太多的效率提升，同时使用上还非常繁琐。
> 
> 如果你有在手机上使用Sshwifty的需要，建议还是插一个蓝牙键盘，这样不但能更有效的使用SSH，还能避免由输入法引入的兼容性问题。

是的，我知道JuiceSSH这个App，但我使用的是iOS设备<sub>~~作为一个学生党家长不给装其他app~~</sub>，我也考虑过外接键盘<sub>~~不过作为学生党买不起~~</sub>，感谢回复
那能否考虑添加自定义组合键呢<sub>至少能用（doge）</sub>

**Comment by nirui** [comment]
但是这个[键盘](https://item.jd.com/100007599117.html)只要￥39.90，蓝牙键盘的平均价格大约在￥150左右。要不您一咬牙一跺脚心动一下？
