### ISSUE TITLE
HTTP Error 431 (Request Header Field(s) Too Large)

### ISSUE THREAD

**Issue by marcomatthijs1** [nirui/sshwifty#86]
I run sshwifty in a docker, along with other services. I connect to sshwifty via HTTPS to avoid the WebCrypt issue, but all others are via regular HTTP (except Nextcloud). When I log into too many services, I get a blank page with the error in the title. It goes away again after I clear all data/cookies related to the server from my browser (FireFox), but then I have to log back in to everything of course.

Any advice? Thank you!

**Comment by nirui** [comment]
There is a hard limit on the maximum allowed size of HTTP headers which was set to 4096 bytes. This value is large enough if Sshwifty is deployed under it's expected running configuration (that is, running in it's own domain/hostname) but may cause problem otherwise.

I have rollback the limit to the default value, which is 1 MBytes. This should reduce the chance of such issue occurring.

But of course, I wouldn't recommend to run multiple services under the same domain/hostname as there are security and maintainability concerns.

The change will become available in the next release which is currently been built. The Docker build usually take hours, please check back later :)

**Comment by marcomatthijs1** [comment]
That's good, looking forward to it then!

Yeah, I know the setup is perhaps a bit niche, but it is not yet under a hostname, it's all local network (for now). I don't think there's a different way to do it for local? I'm relatively new to this so please let me know if I did my setup wrong.

Do I wait to close the issue until I have tested out the new version? I'm also new to opening issues, haha.

**Comment by nirui** [comment]
Keep the issue open if you like to help confirm the fix, thank you for your time :)

You can deploy services in your local network and allocate different domains for each of them, but that requires a local DNS server (can be done via an OpenWRT/DD-WRT router).

The basic idea is this: 

1. On the DNS server, you point a wildcard domain (say `server.local`) to a host in your LAN, so everything `.server.local` will point to that host.
2. On the host, you install NextCloud, Sshwifty etc and most importantly Nginx (as reverse proxy to re-use port 80 and 443), then setup Nginx to forward requests intended for `nextcloud.server.local` to the NextCloud service, and requests intended for `sshwifty.server.local` to Sshwifty service.

It will make your LAN look more "professional" and "organized" if that's the vibe you're going for, but it's indeed quite a hassle. So if you don't want to do that, maybe the fix will resolve the issue so you don't have to change anything (other than deploy the new version of course) ;-)

**Comment by marcomatthijs1** [comment]
Hey, thanks man! 

I think AdguardHome actually has the functionality to redirect domains, so I should be able to set that up. I also already had Caddy set up to do the reverse proxy work but I wasn't gonna bother yet until I felt confident enough to set up remote access to my services.

Thanks for going out of your way to explain an off-topic subject, I really appreciate it!

I'll keep the issue open until I can confirm the bug is fixed then.

**Comment by nirui** [comment]
The new version is available for download, you can pull it now via `docker pull niruix/sshwifty` :)

**Comment by marcomatthijs1** [comment]
That seems to have done it! Good work and thanks for the quick fix. Issue closed.
