### ISSUE TITLE
Guacamole alternative?

### ISSUE THREAD

**Issue by Macleykun** [nirui/sshwifty#88]
Heya!
I saw your project and was wondering if it would also be possible to host it on a rpi, and access it's terminal trough this sshwifty browser.
I can't really forward the ssh port from my home network to my domain, as cloudflare blocks that sorta stuff (i do use nginx proxy manager).
Need to keep the proxy up to hide my public ip :P sorry if this question is out of place/stupid.

**Comment by nirui** [comment]
Hi, Sshwifty can be hosted on a Raspberry Pi, assuming you're running Linux on the Pi. Just use the ARM or ARM64 binary :-)

**Comment by Macleykun** [comment]
ooh awsome!
So, let's say i would host this in a container on my pi.
If i login from remote location X, go on sshwify, can i then enter the internal ip of my pi and ssh into it that way?
Or would sshwifty soley work from the client, and thus not make the connection to my pi?

**Comment by nirui** [comment]
Your first assumption is true. If you host Sshwifty inside your LAN, you can then connect to the target SSH server via their LAN IP address such as `192.168.0.1` as if you're inside the LAN as well.

**Comment by Macleykun** [comment]
Heya!
Thanks for everything so far :D i had a bit of an issue to setup the login with my original private key i use for the server (it's a .ppk).
I don't use putty anymore, but i believe this .ppk format is outdated/not as good is it?

Anyhow, with a new rsa pair i got in! I realised only now i was using .pkk and it would make more sense that i remade my private key but with ssh-keygen.

This new pair also worked in one go! I always used puttygen/mobaxterm tools to make a keypair :P thank you for changing up my keyfile to something more open!

**Comment by nirui** [comment]
I'm not really familiar with PPK file format. Based on my search, it's a special file format for Putty. 

Sshwifty on the other hand, supports unencrypted OpenSSH key format, which is what `ssh` command supports.
