### ISSUE TITLE
doubts when setting environment variable

### ISSUE THREAD

**Issue by laurielylourenco** [nirui/sshwifty#91]
Hi
  I have a doubt about how to configure a private key. From what I understand, seeing other issues, it is possible to pass only the content of the private key by configuring a file type
sshwifty.conf.json

![image](https://user-images.githubusercontent.com/49760702/166947967-39877f06-7e70-4304-a6af-0e63475fd76d.png)
 
And then run command
`sudo docker run --detach \
  --restart always \
  --publish 8182:8182 \
  --env SSHWIFTY_PRESETS="$(cat ./sshwifty.conf.json)" \
  --name sshwifty \
  niruix/sshwifty:latest`

But when I go to check the sswifty environment variables, nothing is set in the SSHWIFTY_PRESETS variable
`sudo docker exec sshwifty env`
And when checking the result of the changes, the same error occurs when selecting the option authentication by private key
Could you give me a hint of what I might be doing wrong?

sorry for english :)

**Comment by nirui** [comment]
Hi :)

The problem was likely caused by special characters (such as `[`, `{` and`"`) in `./sshwifty.conf.json` file. You need to escape those characters, so shell will not expand them into something else.

To setup Presets with `SSHWIFTY_PRESETS` environment variable, you need to:

1. First, prepare `sshwifty.presets.json` file, which should contain all and just the content from the `"Presets"` node of your `sshwifty.conf.json`. For example: 

       [
           {
               "Title": "Desenvol...",
               "Type": "SSH",
               "Host": "localhost",
               "Meta": {
                   "User": "root",
                   "Encoding": "utf-8",
                   "Private Key": "file:///path/your-private-key-file",
                   "Authentication": "Private Key",
                   "Fingerprint": "SHA256:bgO...."
               }
           }
       ]

   Note you can replace the content of `Private Key` with `file:///path/your-private-key-file`, so the value will be loaded from file `/path/your-private-key-file`. The file must exist inside the container, so it can be read by Sshwifty.

   Also note that, everything under `"Meta"` will be sent to your clients. Meaning everyone, your visitors/guests, can read those data including `Private Key`. Be very aware of what you're doing.

2. Then, when deploying Sshwifty, load the `sshwifty.presets.json` file with  `--env SSHWIFTY_PRESETS=$(printf '%q\n' $(cat preset.json.example))`. After that, you might want to check the logs to see if there is any problem occurred during start up.

**Comment by uxfion** [comment]
> Hi :) 你好 ：）
> 
> The problem was likely caused by special characters (such as `[`, `{` and`"`) in `./sshwifty.conf.json` file. You need to escape those characters, so shell will not expand them into something else.该问题可能是由`./sshwifty.conf.json`文件中的特殊字符（例如`[` 、 `{`和`"` ）引起的。您需要转义这些字符，这样 shell 就不会将它们扩展为其他字符。
> 
> To setup Presets with `SSHWIFTY_PRESETS` environment variable, you need to:要使用`SSHWIFTY_PRESETS`环境变量设置预设，您需要：
> 
> 1. First, prepare `sshwifty.presets.json` file, which should contain all and just the content from the `"Presets"` node of your `sshwifty.conf.json`. For example:首先，准备`sshwifty.presets.json`文件，该文件应包含`sshwifty.conf.json`的`"Presets"`节点中的所有内容。例如：
>    ```
>    [
>        {
>            "Title": "Desenvol...",
>            "Type": "SSH",
>            "Host": "localhost",
>            "Meta": {
>                "User": "root",
>                "Encoding": "utf-8",
>                "Private Key": "file:///path/your-private-key-file",
>                "Authentication": "Private Key",
>                "Fingerprint": "SHA256:bgO...."
>            }
>        }
>    ]
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Note you can replace the content of `Private Key` with `file:///path/your-private-key-file`, so the value will be loaded from file `/path/your-private-key-file`. The file must exist inside the container, so it can be read by Sshwifty.请注意，您可以将`Private Key`的内容替换为 `file:///path/your-private-key-file` ，因此将从文件`/path/your-private-key-file`加载该值。该文件必须存在于容器内，以便 Sshwifty 可以读取它。
>    Also note that, everything under `"Meta"` will be sent to your clients. Meaning everyone, your visitors/guests, can read those data including `Private Key`. Be very aware of what you're doing.另请注意， `"Meta"`下的所有内容都将发送给您的客户。这意味着每个人，您的访客/客人，都可以读取这些数据，包括`Private Key` 。非常清楚自己在做什么。
> 2. Then, when deploying Sshwifty, load the `sshwifty.presets.json` file with  `--env SSHWIFTY_PRESETS=$(printf '%q\n' $(cat preset.json.example))`. After that, you might want to check the logs to see if there is any problem occurred during start up.然后，在部署 Sshwifty 时，加载`sshwifty.presets.json`文件 `--env SSHWIFTY_PRESETS=$(printf '%q\n' $(cat preset.json.example))` 。之后，您可能需要检查日志以查看启动过程中是否出现任何问题。

我完全使用你提供的sshwifty.presets.json，但是使用了`docker-compose.yml`来搭建

```
services:
  sshwifty:
    image: niruix/sshwifty:latest
    container_name: sshwifty
    restart: unless-stopped
    ports:
      - 172.17.0.1:8182:8182
    volumes:
      - ./config:/etc/sshwifty
    environment:
      - SSHWIFTY_PRESETS=/etc/sshwifty/sshwifty.presets.json
      # - SSHWIFTY_CONFIG=/etc/sshwifty/sshwifty.conf.example.json
```
却无法运行，docker日志如下：
```
sshwifty  |  Sshwifty Web SSH Client
sshwifty  |
sshwifty  |  Copyright (C) Ni Rui <ranqus@gmail.com>
sshwifty  |  https://github.com/nirui/sshwifty
sshwifty  |
sshwifty  | [INF] Wed, 16 Oct 2024 12:53:34 UTC Sshwifty: Initializing
sshwifty  | [INF] Wed, 16 Oct 2024 12:53:34 UTC Sshwifty > Configuration > Redundant: Loading configuration from one of the default configuration files ...
sshwifty  | [WRN] Wed, 16 Oct 2024 12:53:34 UTC Sshwifty > Configuration > Redundant: Unable to load configuration from "File": Configuration file was not specified. Also tried fallback files "/home/sshwifty/.config/sshwifty.conf.json", "/etc/sshwifty.conf.json", "/sshwifty.conf.json", but none of it was available
sshwifty  | [INF] Wed, 16 Oct 2024 12:53:34 UTC Sshwifty > Configuration > Redundant: Loading configuration from environment variables ...
sshwifty  | [WRN] Wed, 16 Oct 2024 12:53:34 UTC Sshwifty > Configuration > Redundant: Unable to load configuration from "Environment Variable": invalid "SSHWIFTY_PRESETS": invalid character '/' looking for beginning of value
sshwifty  | [ERR] Wed, 16 Oct 2024 12:53:34 UTC Sshwifty: "Redundant" loader cannot load configuration: all existing redundant loader has failed
sshwifty  | [ERR] Wed, 16 Oct 2024 12:53:34 UTC Sshwifty: Unable to start due to error: all existing redundant loader has failed
sshwifty  | [INF] Wed, 16 Oct 2024 12:53:34 UTC Sshwifty: Closed
```

请问我是哪里写错了吗？

**Comment by nirui** [comment]
Hi @uxfion，`SSHWIFTY_PRESETS`环境变量是依照直接输入读取的，而不是从文件中读取。如果想使用`SSHWIFTY_PRESETS`，你需要将Presets设置直接载入进`SSHWIFTY_PRESETS`环境变量（通过类似`SSHWIFTY_PRESETS=$(cat sshwifty.presets.json)`的办法）。

如果你想通过文件来指定Presets，将Preset项直接写入配置文件即可，请参考`sshwifty.conf.example.json`中的样例。

**Comment by uxfion** [comment]
（没想到会回那么快）感谢解答，我以为会像`SSHWIFTY_CONFIG`一样直接从file中读取。现在清楚了，谢谢🙏！
