### ISSUE TITLE
是否可以支持中文界面？

### ISSUE THREAD

**Issue by gmzta** [nirui/sshwifty#94]
另外，我想我的程序里面集成您的工具，是否需要授权？

**Comment by nirui** [comment]
你好！

与授权有关的条款都已在[LICENSE.md]中列出，请自行参考其中的说明。

关于中文界面方面，目前我还没有添加多语言支持的计划，抱歉。如果有需要的话，您可以按上面所提到的协议自行Fork、翻译并进行维护和分发。

[LICENSE.md]: https://github.com/nirui/sshwifty/blob/02f14eb14fdff62ed11844b967dd93eaa7849f00/LICENSE.md
