### ISSUE TITLE
Edge连接SSH后Terminal中无法调出输入法

### ISSUE THREAD

**Issue by playGitboy** [nirui/sshwifty#95]
**一、问题反馈**
Edge连接SSH后Terminal中无法调出输入法（测试了多种输入法），即Terminal中光标闪烁但切换任何输入法均无法输入任何字符——同等环境下Chrome中输入正常

系统：Windows11 21H2
浏览器：Microsoft Edge 版本 101.0.1210.39 (正式版本) (64 位)

**二、建议**
填写SSH配置的界面布局，建议Host第一行User第二行；Authentication处建议默认选中**Password**（目前是默认未选择任何一项），更符合通用习惯；

**Comment by nirui** [comment]
你好！

我这边没有运行Windows系统的机器，调试可能会比较困难。

请问你能在 https://xtermjs.org/ 页面上的演示终端里输入文本么？如果你能在演示页面正常输入，而在Sshwifty里则不行，可能是Sshwifty中存在Bug。

此外，还可以观察一下当你在Edge中进行输入的时候，浏览器调试控制台（通常通过F12调出）中是否有错误信息的输出。如果有的话，烦请提供一下方便我这里进行检查。

感谢。

**Comment by playGitboy** [comment]
好吧在Edlge中测试了https://xtermjs.org/ 演示终端也无法调用输入法 那估计是xtermjs的bug了

**Comment by nirui** [comment]
我刚才去看了一眼xtermjs仓库的Issue列表，没发现与Edge相关的兼容性问题（有一个Issue但是是去年的，而且已关闭），所以觉得很奇怪。

要不你试试看去那边发个Issue询问一下？我这边短时间大概没法找到能部署Windows 11的机器，所以没法继续测试，抱歉啦。

如果你接下来有新的信息想要告知的话，请更新这个Issue :)

**Comment by playGitboy** [comment]
经测试其他计算机同等系统条件下edge打开xtermjs输入法暂未发现调用问题
目前怀疑根本原因是本机系统win11精简版带来的影响(怀疑系统精简了部分输入法组件导致，但不解的是系统已安装手心输入法，在其他网站或程序中均未出现过任何输入问题，目前仅发现xtermjs出现兼容问题)，考虑到该兼容性BUG其他人不易复现，也暂不向xtermjs提issue，谢谢  

**优化建议**
1. 建议增加rz/sz支持（该实用功能已渐成新版ssh工具标配）
2. 填写SSH配置的界面布局，建议Host第一行User第二行；Authentication处建议默认选中Password（目前是默认未选择任何一项），更符合通用习惯；

**Comment by nirui** [comment]
就目前的情况，我只能保证会去研究rz/sz功能（见#51），因为我还不能确定添加新的功能会不会影响我对Sshwifty未来的计划。但是未来Sshwifty是会有某种基于SSH的文件管理功能的，缺少了这些功能我自己用起来也不是很方面。

另外，认证方式默认启用Password的提议大概不太会被满足了。因为：1）用户需要主观的关注到自己所选择的选项；2）更重要的是，未来Sshwifty会使用更友好的方式来提示用户进行认证方式的选择，而不是像目前这样将所有Sshwifty支持但目标服务器不一定支持的验证方式暴力的列出来。因此目前我觉得还是不去改动比较好。

最后，Host和User这两个表单的排序我稍后会遵照你的提议修改。因为用户在连接时，确实是会先考虑目标Host，然后才是User。你提议的顺序才是符合使用逻辑的，感谢！:D
