### ISSUE TITLE
Error using behind Traefik + NGINX proxy

### ISSUE THREAD

**Issue by hwittenborn** [nirui/sshwifty#96]
I run Sshwifty behind a Traefik proxy, which in turn is behind an NGINX proxy. The only header modifications done in my NGINX config are the addition of the `X-Real-IP` and `X-Forwarded-Proto` headers, and none are manually set in my Traefik config.

With that, I can log into my Sshwifty instance just fine, but any time I attempt to set up a new SSH server, I get the following error:

![image](https://user-images.githubusercontent.com/74838472/168937132-6ebc522a-0910-4547-a662-81bb6009d240.png)

Docker logs also show the following error:

```
[WRN] Wed, 18 May 2022 01:14:45 UTC Sshwifty > Server (0.0.0.0:8182) > Client (172.29.0.1:36502): Request ended with error: /sshwifty/socket: HTTP Error (400): websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
```

Running Sshwifty locally is working just fine, so it seems like something's happening during the proxying, though I can't figure out what at all.

Anything I might want to try? I run various other services through my NGINX + Traefik proxy and they all work fine, so I'm not thinking that's too much related.

**Comment by nirui** [comment]
A few tweaks are required for Nginx to proxy websocket connections, see https://www.nginx.com/blog/websocket-nginx/. More specifically, you need to setup `map` settings in your Nginx configuration. Example:

    http {
        map $http_upgrade $connection_upgrade {
            default upgrade;
            '' close;
        }

        server {
            .... server configuration goes here ....
        }

        server { .... }

        .... other http settings ....
    }

Traefik on the other hand, comes with Websocket support enabled.

Hope it helped :)

**Comment by hwittenborn** [comment]
Thank you! Both for the very quick response, and the help with my use case that most people probably don't have. I'll be sure to aim for the same mindset in my own projects going forward :)

P.s. everything worked great after looking through that link you sent. Thanks again!
