### ISSUE TITLE
Send F10 command to server

### ISSUE THREAD

**Issue by Zariaa27** [nirui/sshwifty#98]
It seems we cannot send an F10 command to ssh, it's bothering because I cannot exit the installimage editor from hetzner.

**Comment by Zariaa27** [comment]
FOUND THE ERROR:
I ahd to press the context menu.. I feel dumb

**Comment by nirui** [comment]
There is a panel which can be opened by clicking current console tab again. On the panel, you can find the `F10` button, which will send `F10` keystroke once clicked. This is useful if `F10` is already been allocated by the browser for something else.

I guess you've already figured it out, congrats! :D
